### ISSUE TITLE
Request compatibility check - fail explicitly when version mismatches

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1007]
## Feature description (Mandatory)

Where APOC relies on internal core features of neo4j that are major or minor version dependent, please put those into try/catch and fail with an explicit "compatibility matrix" message.

It's OK to fail, but would want the failure to be apoc-specific and meaningful, something like "Basic assumption violated, are you using the right version of APOC with the right version of Neo4j?"

## How this feature can improve the project?

Recently I used the wrong version of APOC with neo4j 3.5.0 -- you get a very large stacktrace which does not implicate APOC, but which we know is caused by APOC.

```
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: 2018-12-05 12:52:39.275+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@58fb7731' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@58fb7731' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@58fb7731' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:122)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@58fb7731' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         ... 3 more
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         ... 5 more
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalKernelExtensions@3bd418e4' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         ... 9 more
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/AvailabilityGuard
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.Class.getDeclaredMethods0(Native Method)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.Class.privateGetPublicMethods(Class.java:2902)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.Class.getMethods(Class.java:1615)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.reflect.WeakCache.get(WeakCache.java:127)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.extension.AbstractKernelExtensions.getKernelExtensionDependencies(AbstractKernelExtensions.java:111)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:59)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         ... 12 more
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.AvailabilityGuard
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]:         ... 28 more
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 pre-neo4j.sh[15410]: 2018-12-05 12:52:39.280+0000 INFO  Neo4j Server shutdown initiated by request
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 systemd[1]: neo4j.service: Main process exited, code=exited, status=1/FAILURE
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 systemd[1]: neo4j.service: Unit entered failed state.
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 systemd[1]: neo4j.service: Failed with result 'exit-code'.
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 systemd[1]: neo4j.service: Service hold-off time over, scheduling restart.
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 systemd[1]: Stopped Neo4j Graph Database.
    amazon-ebs: Dec 05 12:52:39 ip-172-31-29-103 systemd[1]: Started Neo4j Graph Database.
```

**Comment by 33eyes** [comment]
On a related note, is it possible to change the link to the Apoc download in the [Apoc install instructions for neo4j server](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_installation_in_neo4j_server_docker) from this https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.4.0.4 link to this: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/ , or something like that?  

I've accidentally downloaded an outdated Apoc version from that link a few times and got the stacktrace above, and kept forgetting that it's caused by Apoc. Updating that link doesn't solve the issue above of course, but it's a simple fix that can help people who follow along those Apoc install instructions to avoid running into this hard-to-track stacktrace.

**Comment by jexp** [comment]
@33eyes where did you take the link from? 
We try to link to the last release from each branch and also have the related major release number in the readme + docs? We could possibly point out better which Neo4j version that release is for?

**Comment by 33eyes** [comment]
@jexp this link comes up as the top result when googling for "neo4j install apoc": https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_installation_in_neo4j_server_docker . It does say that it's a user guide for Apoc 3.4.0 at the top of the page, but when I've used it I just assumed that it's the latest version of Apoc that would work with the latest version of neo4j, which is my mistake for not checking the releases, but it looks like other people are doing the same thing, e.g.: https://community.neo4j.com/t/cannot-install-apoc-3-4-0-4-on-neo4j-community-3-5-1/4071

**Comment by jexp** [comment]
Good point, I'll improve the wording around it and also add a link to "all releases"

**Comment by sarmbruster** [comment]
neo4j 3.5.3 and onwards should spit out a more reasonable error message if the version does not match, see https://github.com/neo4j/neo4j/commit/45c3a07d9748221f4be807675c2da2b3e746c607

**Comment by 33eyes** [comment]
Thanks!
