### ISSUE TITLE
java.lang.NullPointerException error in apoc.load.jdbc with advantage jdbc driver

### ISSUE THREAD

**Issue by pdrangeid** [neo4j-contrib/neo4j-apoc-procedures#1084]
## Expected Behavior (Mandatory)
Return rows of data

## Actual Behavior (Mandatory)
can get SOME data, but when trying with larger datasets I get the failure with message:

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.lang.NullPointerException

## How to Reproduce the Problem
using jdbc driver: com.extendedsystems.jdbc.advantage.ADSDriver

querying an advantage SQL datasource where I will be receiving over 40000 records back.
example query I'm using: call apoc.load.jdbc('jdbc:extendedsystems:advantage://edc-commitcrm:6262;catalog=//edc-commitcrm.tdonline.com/CommitCRM/Db','SELECT RECID,SLIPDATE,WORKERID,CARDID,TICKETID,ITEMID,DESCRIPTION,HOURSAMOUNT,QUANTITY,PRICE,TOTAL,STAGE,BILLKIND,CREATEDATE,UPDATEDATE,UPDATEUSER,
CREATEUSER,USER1,CONTACTID,BCRECID,BCCODE,FROMTIME,TOTIME from slips WHERE CREATEDATE > \''+lastnewcharge+'\' AND CREATEDATE > \''+historylimit+'\'') yield row
return row

other JDBC queries against the SAME database ARE working.  This is the largest query I do, so maybe it has to do with the volume of data.

### Simple Dataset (where it's possibile)

not possible without an advantage datasource

### Steps (Mandatory)

  1. perform above query against advantage sql database where you expect a larger (10s of thousands) of records to be returned.
  1.
  1.

## Specifications (Mandatory)

Currently used versions
This query works fine (against the same dataset) on:
OS: Windows Server 2016 Datacenter
Neo4j Server version: 3.4.9 
apoc-3.4.0.3-test-jdbc.jar (Michael had compiled a test version of apoc to support the advantage jdbc methods)

It fails running on:
Windows Server 2019
Neo4j Server version 3.5.2
Running apoc apoc-3.5.0.1-all.jar

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by jexp** [comment]
Are there any details in the logs?

**Comment by pdrangeid** [comment]
Never looked much at the logs before in Neo/APOC.  Can you tell my which
ones I should examine?

**Comment by pdrangeid** [comment]
2019-02-04 13:58:56 Commons Daemon procrun stdout initialized
2019-02-04 21:59:01.021+0000 INFO  ======== Neo4j 3.5.2 ========
2019-02-04 21:59:01.052+0000 INFO  Starting...
2019-02-04 21:59:20.771+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2019-02-04 21:59:23.974+0000 INFO  Started.
2019-02-04 21:59:25.709+0000 INFO  Remote interface available at http://localhost:7474/
2019-02-04 21:59:44.412+0000 WARN  The client is unauthorized due to authentication failure.
2019-02-04 22:01:23.662+0000 ERROR Cannot execute read result-set.
Error:
null
java.lang.NullPointerException
	at apoc.load.Jdbc$ResultSetIterator.convert(Jdbc.java:223)
	at apoc.load.Jdbc$ResultSetIterator.get(Jdbc.java:208)
	at apoc.load.Jdbc$ResultSetIterator.next(Jdbc.java:199)
	at apoc.load.Jdbc$ResultSetIterator.next(Jdbc.java:163)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure$MappingIterator.hasNext(ReflectiveProcedureCompiler.java:701)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder$1.hasNext(AllStoreHolder.java:1075)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$$anon$1.hasNext(CallSupport.scala:167)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply$mcZ$sp(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1.hasNext(ExceptionTranslationSupport.scala:49)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.neo4j.cypher.internal.runtime.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:53)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:76)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.accept(StandardInternalExecutionResult.scala:192)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$safelyAndClose$1.apply(ClosingExecutionResult.scala:171)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.safelyAndClose(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:157)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:73)
	at org.neo4j.bolt.v1.messaging.ResultHandler.onRecords(ResultHandler.java:40)
	at org.neo4j.bolt.v3.runtime.StreamingState.lambda$processStreamResultMessage$0(StreamingState.java:41)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:484)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:328)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
	at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
	at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-02-04 22:12:15.459+0000 ERROR Cannot execute read result-set.
Error:
null
java.lang.NullPointerException
	at apoc.load.Jdbc$ResultSetIterator.convert(Jdbc.java:223)
	at apoc.load.Jdbc$ResultSetIterator.get(Jdbc.java:208)
	at apoc.load.Jdbc$ResultSetIterator.next(Jdbc.java:199)
	at apoc.load.Jdbc$ResultSetIterator.next(Jdbc.java:163)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure$MappingIterator.hasNext(ReflectiveProcedureCompiler.java:701)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder$1.hasNext(AllStoreHolder.java:1075)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$$anon$1.hasNext(CallSupport.scala:167)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply$mcZ$sp(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1.hasNext(ExceptionTranslationSupport.scala:49)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:118)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:61)
	at org.neo4j.cypher.internal.compatibility.InterpretedRuntime$InterpretedExecutionPlan.run(InterpretedRuntime.scala:84)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:205)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:102)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
	at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-02-05 15:20:57.843+0000 ERROR Cannot execute read result-set.
Error:
null
java.lang.NullPointerException
	at apoc.load.Jdbc$ResultSetIterator.convert(Jdbc.java:223)
	at apoc.load.Jdbc$ResultSetIterator.get(Jdbc.java:208)
	at apoc.load.Jdbc$ResultSetIterator.next(Jdbc.java:199)
	at apoc.load.Jdbc$ResultSetIterator.next(Jdbc.java:163)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure$MappingIterator.hasNext(ReflectiveProcedureCompiler.java:701)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder$1.hasNext(AllStoreHolder.java:1075)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$$anon$1.hasNext(CallSupport.scala:167)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply$mcZ$sp(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:49)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
	at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$$anon$1.hasNext(ExceptionTranslationSupport.scala:49)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:118)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:61)
	at org.neo4j.cypher.internal.compatibility.InterpretedRuntime$InterpretedExecutionPlan.run(InterpretedRuntime.scala:84)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:205)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:102)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
	at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by pdrangeid** [comment]
Also - confirmed this problem also existed in APOC 3.4.04 on Neo4j 3.4.12

I believe it ONLY worked completely properly on the custom test version you compiled for me...

**Comment by pdrangeid** [comment]
One more item, it appears the datatype that is causing the problem is TIME.  (not datetime) - if I exclude the columns that have the TIME type, I avoid the error...  FOr the time being, I can just CAST the time as a different datatype

**Comment by jexp** [comment]
@pdrangeid thanks a lot fo the detailed feedback this will help us to solve the issue.

**Comment by conker84** [comment]
@jexp this is fixed in v 3.4 by #1056 do you think we should rebase the v 3.5 or do a PR?

**Comment by conker84** [comment]
@jexp the bug was fixed in v 3.4 by #1039, do you think we should rebase the v 3.5 or do a PR?

**Comment by jexp** [comment]
Ok, then it will make it in the next release.
