### ISSUE TITLE
file utils constraints test errors

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1099]
```
apoc.util.FileUtilsTest > changeFileDoubleSlashesUrlWithDirectoryImportConstrainedURIWithDirectoryImport FAILED
    org.junit.ComparisonFailure: expected:<...java/neo/procs/apoc/[target/test-data/impermanent-db/import/test.csv]> but was:<...java/neo/procs/apoc/[]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at apoc.util.FileUtilsTest.changeFileDoubleSlashesUrlWithDirectoryImportConstrainedURIWithDirectoryImport(FileUtilsTest.java:70)

apoc.util.FileUtilsTest > changeSlashUrlWithDirectoryImportConstrainedURIWithDirectoryImport FAILED
    org.junit.ComparisonFailure: expected:<file:/[Users/mh/d/java/neo/procs/apoc/target/test-data/impermanent-db/import/]test.csv> but was:<file:/[]test.csv>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at apoc.util.FileUtilsTest.changeSlashUrlWithDirectoryImportConstrainedURIWithDirectoryImport(FileUtilsTest.java:60)

apoc.util.FileUtilsTest > importDirectoryWithRelativePathWithDirectoryImport FAILED
    org.junit.ComparisonFailure: expected:<...ava/neo/procs/apoc/t[arget/test-data/impermanent-db/import/t]est.csv> but was:<...ava/neo/procs/apoc/t[]est.csv>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at apoc.util.FileUtilsTest.importDirectoryWithRelativePathWithDirectoryImport(FileUtilsTest.java:80)

apoc.util.FileUtilsTest > changeNoSlashesUrlWithDirectoryImportConstrainedURIWithDirectoryImport FAILED
    org.junit.ComparisonFailure: expected:<...ava/neo/procs/apoc/t[arget/test-data/impermanent-db/import/t]est.csv> but was:<...ava/neo/procs/apoc/t[]est.csv>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at apoc.util.FileUtilsTest.changeNoSlashesUrlWithDirectoryImportConstrainedURIWithDirectoryImport(FileUtilsTest.java:55)

apoc.util.FileUtilsTest > changeFileSlashUrlWithDirectoryImportConstrainedURIWithDirectoryImport FAILED
    org.junit.ComparisonFailure: expected:<file:/[Users/mh/d/java/neo/procs/apoc/target/test-data/impermanent-db/import/]test.csv> but was:<file:/[]test.csv>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at apoc.util.FileUtilsTest.changeFileSlashUrlWithDirectoryImportConstrainedURIWithDirectoryImport(FileUtilsTest.java:65)

apoc.util.FileUtilsTest > changeFileTripleSlashesUrlWithDirectoryImportConstrainedURIWithDirectoryImport FAILED
    org.junit.ComparisonFailure: expected:<file:/[Users/mh/d/java/neo/procs/apoc/target/test-data/impermanent-db/import/]test.csv> but was:<file:/[]test.csv>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at apoc.util.FileUtilsTest.changeFileTripleSlashesUrlWithDirectoryImportConstrainedURIWithDirectoryImport(FileUtilsTest.java:75)

```

**Comment by jexp** [comment]
```
apoc.load.relative.LoadRelativePathTest > testLoadRelativePathSimple FAILED
    org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.load.xmlSimple`: Caused by: java.io.FileNotFoundException: /xml/databases.xml (No such file or directory)
        at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:83)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:428)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:411)
        at apoc.util.TestUtil.testResult(TestUtil.java:90)
        at apoc.util.TestUtil.testCall(TestUtil.java:39)
        at apoc.util.TestUtil.testCall(TestUtil.java:35)
        at apoc.load.relative.LoadRelativePathTest.testLoadRelativePathSimple(LoadRelativePathTest.java:95)

        Caused by:
        org.neo4j.kernel.impl.query.QueryExecutionKernelException: Failed to invoke procedure `apoc.load.xmlSimple`: Caused by: java.io.FileNotFoundException: /xml/databases.xml (No such file or directory)
            at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:65)
            at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:79)
            ... 6 more

            Caused by:
            org.neo4j.cypher.CypherExecutionException: Failed to invoke procedure `apoc.load.xmlSimple`: Caused by: java.io.FileNotFoundException: /xml/databases.xml (No such file or directory)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:50)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:57)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:41)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.callReadOnlyProcedure(ExceptionTranslatingQueryContext.scala:146)
                at org.neo4j.cypher.internal.runtime.LazyReadOnlyCallMode.callProcedure(ProcedureCallMode.scala:47)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureExecutionResult.executeCall(ProcedureExecutionResult.scala:73)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureExecutionResult.<init>(ProcedureExecutionResult.scala:69)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureCallExecutionPlan.createNormalExecutionResult(ProcedureCallExecutionPlan.scala:90)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureCallExecutionPlan.run(ProcedureCallExecutionPlan.scala:80)
                at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(LatestRuntimeVariablePlannerCompatibility.scala:128)
                at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(LatestRuntimeVariablePlannerCompatibility.scala:124)
                at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
                at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper.run(LatestRuntimeVariablePlannerCompatibility.scala:124)
                at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
                at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:119)
                at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
                ... 7 more

                Caused by:
                org.neo4j.internal.kernel.api.exceptions.ProcedureException: Failed to invoke procedure `apoc.load.xmlSimple`: Caused by: java.io.FileNotFoundException: /xml/databases.xml (No such file or directory)
                    at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.newProcedureException(ReflectiveProcedureCompiler.java:766)
                    at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:662)
                    at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:219)
                    at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:290)
                    at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:1072)
                    at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallRead(AllStoreHolder.java:830)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$4.apply(TransactionBoundQueryContext.scala:866)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$4.apply(TransactionBoundQueryContext.scala:866)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.scala:939)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadOnlyProcedure(TransactionBoundQueryContext.scala:868)
                    at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callReadOnlyProcedure$1.apply(ExceptionTranslatingQueryContext.scala:146)
                    at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callReadOnlyProcedure$1.apply(ExceptionTranslatingQueryContext.scala:146)
                    at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
                    ... 23 more

                    Caused by:
                    java.lang.RuntimeException: Can't read url invalid URL (/xml/databases.xml) as XML
                        at apoc.load.Xml.xmlToMapResult(Xml.java:119)
                        at apoc.load.Xml.xmlSimple(Xml.java:57)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:648)
                        ... 34 more

                        Caused by:
                        java.io.FileNotFoundException: /xml/databases.xml (No such file or directory)
                            at java.io.FileInputStream.open0(Native Method)
                            at java.io.FileInputStream.open(FileInputStream.java:195)
                            at java.io.FileInputStream.<init>(FileInputStream.java:138)
                            at java.io.FileInputStream.<init>(FileInputStream.java:93)
                            at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
                            at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
                            at apoc.load.Xml.getXMLStreamReaderFromUrl(Xml.java:128)
                            at apoc.load.Xml.xmlToMapResult(Xml.java:111)
                            ... 40 more

```

**Comment by jexp** [comment]
several tests in this one

```
apoc.export.csv.ImportCsvLdbcTest > testLdbc FAILED
    org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.import.csv`: Caused by: java.io.FileNotFoundException: /forum.csv (No such file or directory)
        at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:83)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:428)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:411)
        at apoc.util.TestUtil.testResult(TestUtil.java:90)
        at apoc.util.TestUtil.testCall(TestUtil.java:39)
        at apoc.export.csv.ImportCsvLdbcTest.testLdbc(ImportCsvLdbcTest.java:172)

        Caused by:
        org.neo4j.kernel.impl.query.QueryExecutionKernelException: Failed to invoke procedure `apoc.import.csv`: Caused by: java.io.FileNotFoundException: /forum.csv (No such file or directory)
            at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:65)
            at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:79)
            ... 5 more

            Caused by:
            org.neo4j.cypher.CypherExecutionException: Failed to invoke procedure `apoc.import.csv`: Caused by: java.io.FileNotFoundException: /forum.csv (No such file or directory)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:50)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:57)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:41)
                at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.callSchemaWriteProcedure(ExceptionTranslatingQueryContext.scala:152)
                at org.neo4j.cypher.internal.runtime.SchemaWriteCallMode.callProcedure(ProcedureCallMode.scala:83)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureExecutionResult.executeCall(ProcedureExecutionResult.scala:73)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureExecutionResult.<init>(ProcedureExecutionResult.scala:69)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureCallExecutionPlan.createNormalExecutionResult(ProcedureCallExecutionPlan.scala:90)
                at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureCallExecutionPlan.run(ProcedureCallExecutionPlan.scala:80)
                at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(LatestRuntimeVariablePlannerCompatibility.scala:128)
                at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(LatestRuntimeVariablePlannerCompatibility.scala:124)
                at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
                at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper.run(LatestRuntimeVariablePlannerCompatibility.scala:124)
                at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
                at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:119)
                at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
                ... 6 more

                Caused by:
                org.neo4j.internal.kernel.api.exceptions.ProcedureException: Failed to invoke procedure `apoc.import.csv`: Caused by: java.io.FileNotFoundException: /forum.csv (No such file or directory)
                    at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.newProcedureException(ReflectiveProcedureCompiler.java:766)
                    at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:662)
                    at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:219)
                    at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:290)
                    at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:1072)
                    at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallSchema(AllStoreHolder.java:875)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$8.apply(TransactionBoundQueryContext.scala:885)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$8.apply(TransactionBoundQueryContext.scala:885)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.scala:939)
                    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callSchemaWriteProcedure(TransactionBoundQueryContext.scala:886)
                    at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callSchemaWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:152)
                    at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callSchemaWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:152)
                    at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
                    ... 22 more

                    Caused by:
                    java.lang.RuntimeException: Error executing in separate thread: java.io.FileNotFoundException: /forum.csv (No such file or directory)
                        at apoc.util.Util.inThread(Util.java:194)
                        at apoc.export.csv.ImportCsv.importCsv(ImportCsv.java:37)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:648)
                        ... 33 more

                        Caused by:
                        java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /forum.csv (No such file or directory)
                            at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                            at java.util.concurrent.FutureTask.get(FutureTask.java:192)
                            at apoc.util.Util.inThread(Util.java:192)
                            ... 39 more

                            Caused by:
                            java.io.FileNotFoundException: /forum.csv (No such file or directory)

apoc.export.csv.ImportCsvTest > testArray FAILED
    org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.import.csv`: Caused by: java.io.FileNotFoundException: /array.csv (No such file or directory)
        at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:83)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:428)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:411)
        at apoc.util.TestUtil.testResult(TestUtil.java:90)
        at apoc.util.TestUtil.testCall(TestUtil.java:39)
        at apoc.export.csv.ImportCsvTest.testArray(ImportCsvTest.java:204)

        Caused by:
 
```

**Comment by jexp** [comment]
Fixed locally.
