### ISSUE TITLE
APOC trigger: deletedNodes does not return info of the Node (properties, labels) only the id in before phase

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1152]
## Expected Behavior (Mandatory)
Apoc trigger should not execute the commit in the `before` phase.
Following the source of the issue:
https://community.neo4j.com/t/apoc-trigger-deletednodes-does-not-return-info-of-the-node-properties-labels-only-the-id-in-before-phase/1403

## Actual Behavior (Mandatory)
Apoc trigger seems execute the commit in the `before` phase. Following the stack trace:

```bash
neo4j    | 2019-04-03 21:22:43.944+0000 INFO  Procedure removeComponent triggered by deletion of node with id 0
neo4j    | 2019-04-03 21:22:43.956+0000 WARN  Error executing trigger remove_components in phase before Node with id 0 has been deleted in this transaction
neo4j    | org.neo4j.graphdb.QueryExecutionException: Node with id 0 has been deleted in this transaction
neo4j    |      at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
neo4j    |      at org.neo4j.cypher.internal.javacompat.ExecutionResult.converted(ExecutionResult.java:406)
neo4j    |      at org.neo4j.cypher.internal.javacompat.ExecutionResult.next(ExecutionResult.java:241)
neo4j    |      at org.neo4j.cypher.internal.javacompat.ExecutionResult.next(ExecutionResult.java:58)
neo4j    |      at org.neo4j.helpers.collection.Iterators.count(Iterators.java:388)
neo4j    |      at org.neo4j.helpers.collection.Iterators.count(Iterators.java:372)
neo4j    |      at apoc.trigger.Trigger$TriggerHandler.lambda$executeTriggers$0(Trigger.java:283)
neo4j    |      at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
neo4j    |      at apoc.trigger.Trigger$TriggerHandler.executeTriggers(Trigger.java:272)
neo4j    |      at apoc.trigger.Trigger$TriggerHandler.beforeCommit(Trigger.java:263)
neo4j    |      at org.neo4j.kernel.internal.TransactionEventHandlers.beforeCommit(TransactionEventHandlers.java:123)
neo4j    |      at org.neo4j.kernel.internal.TransactionEventHandlers.beforeCommit(TransactionEventHandlers.java:48)
neo4j    |      at org.neo4j.kernel.impl.api.TransactionHooks.beforeCommit(TransactionHooks.java:59)
neo4j    |      at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:649)
neo4j    |      at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:579)
neo4j    |      at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:178)
neo4j    |      at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:469)
neo4j    |      at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:329)
neo4j    |      at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
neo4j    |      at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
neo4j    |      at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
neo4j    |      at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
neo4j    |      at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
neo4j    |      at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
neo4j    |      at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
neo4j    |      at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
neo4j    |      at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
neo4j    |      at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
neo4j    |      at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
neo4j    |      at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
neo4j    |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
neo4j    |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
neo4j    |      at java.lang.Thread.run(Thread.java:748)
neo4j    | Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Node with id 0 has been deleted in this transaction
neo4j    |      ... 32 more
neo4j    | Caused by: org.neo4j.cypher.EntityNotFoundException: Node with id 0 has been deleted in this transaction
neo4j    |      at org.neo4j.cypher.exceptionHandler$.entityNotFoundException(exceptionHandler.scala:56)
neo4j    |      at org.neo4j.cypher.exceptionHandler$.entityNotFoundException(exceptionHandler.scala:26)
neo4j    |      at org.neo4j.cypher.internal.v3_5.util.EntityNotFoundException.mapToPublic(CypherException.scala:45)
neo4j    |      at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:94)
neo4j    |      at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.org$neo4j$cypher$internal$compatibility$ClosingExecutionResult$$safely(ClosingExecutionResult.scala:167)
neo4j    |      at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1$$anon$1.next(ClosingExecutionResult.scala:77)
neo4j    |      at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1$$anon$1.next(ClosingExecutionResult.scala:76)
neo4j    |      at org.neo4j.cypher.internal.javacompat.ExecutionResult.next(ExecutionResult.java:237)
neo4j    |      ... 30 more
neo4j    | Caused by: org.neo4j.cypher.internal.v3_5.util.EntityNotFoundException: Node with id 0 has been deleted in this transaction
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.getLabelsForNode(TransactionBoundQueryContext.scala:154)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$getLabelsForNode$1.apply(ExceptionTranslatingQueryContext.scala:62)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$getLabelsForNode$1.apply(ExceptionTranslatingQueryContext.scala:62)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:41)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.getLabelsForNode(ExceptionTranslatingQueryContext.scala:62)
neo4j    |      at org.neo4j.cypher.operations.CypherFunctions.labels(CypherFunctions.java:719)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.LabelsFunction.compute(LabelsFunction.scala:30)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.NullInNullOutExpression.apply(NullInNullOutExpression.scala:32)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.CoerceTo.apply(CoerceTo.scala:31)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.FunctionInvocation$$anonfun$1.apply(FunctionInvocation.scala:34)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.FunctionInvocation$$anonfun$1.apply(FunctionInvocation.scala:33)
neo4j    |      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
neo4j    |      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
neo4j    |      at scala.collection.Iterator$class.foreach(Iterator.scala:891)
neo4j    |      at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
neo4j    |      at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
neo4j    |      at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
neo4j    |      at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
neo4j    |      at scala.collection.AbstractTraversable.map(Traversable.scala:104)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.FunctionInvocation.apply(FunctionInvocation.scala:33)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.Add.apply(Add.scala:30)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.CoerceTo.apply(CoerceTo.scala:31)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$384ee436d84d66a2071d328bd626e5e$$$$ingThrough$1$$anonfun$6.apply(ProcedureCallPipe.scala:89)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$384ee436d84d66a2071d328bd626e5e$$$$ingThrough$1$$anonfun$6.apply(ProcedureCallPipe.scala:89)
neo4j    |      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
neo4j    |      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
neo4j    |      at scala.collection.Iterator$class.foreach(Iterator.scala:891)
neo4j    |      at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
neo4j    |      at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
neo4j    |      at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
neo4j    |      at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
neo4j    |      at scala.collection.AbstractTraversable.map(Traversable.scala:104)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$47ed39fa0ef53517ef6c6e9ff19f46$$$$sultsByPassingThrough$1.apply(ProcedureCallPipe.scala:89)
neo4j    |      at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$47ed39fa0ef53517ef6c6e9ff19f46$$$$sultsByPassingThrough$1.apply(ProcedureCallPipe.scala:88)
neo4j    |      at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
neo4j    |      at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
neo4j    |      at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult$$anon$1.next(PipeExecutionResult.scala:52)
neo4j    |      at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult$$anon$1.next(PipeExecutionResult.scala:48)
neo4j    |      at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1$$anon$1$$anonfun$next$1.apply(ClosingExecutionResult.scala:80)
neo4j    |      at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$javaIterator$1$$anon$1$$anonfun$next$1.apply(ClosingExecutionResult.scala:78)
neo4j    |      at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
neo4j    |      ... 34 more
```

## How to Reproduce the Problem

```
call apoc.trigger.add('remove_components', "UNWIND {deletedNodes} as node call apoc.log.info('Procedure removeComponent triggered by deletion of node with id ' + id(node)) call apoc.log.info('Extra info of node with id ' + id(node) + ', labels: ' + apoc.text.join(labels(node), ',')) return true" ,{phase:'before'})
```
Then remove a node

### Simple Dataset (where it's possibile)

```
create (n:Person:`@Foo`{name:'Andrea'}) return n
```

### Steps (Mandatory)

  1. Create the trigger
  1. Add a node
  1. Remove the node

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Docker
  - Neo4j: 3.5.3
  - Neo4j-Apoc: 3.5.0.2

**Comment by borick** [comment]
This is impacting us as we're trying to store audit of delete information and that can't be obtained currently afaik

**Comment by IkKan** [comment]
+1 for this. 
I was trying to call apoc.es.post() with node properties on delete...

**Comment by daegeunhaha** [comment]
+1 for this.

**Comment by Marc-Roth** [comment]
+1
As we need to have an audit trail per node.
