### ISSUE TITLE
classpath in docker Neo4j image

### ISSUE THREAD

**Issue by thomasricaud** [neo4j-contrib/neo4j-apoc-procedures#1170]
Hi all,

When running a neo4j container with the apoc plugin i got an error ClassDefNotFound.

Do you have any Dockerfile that would include the APOC plugin ?
Should i add some specific dependency to my container ?

## Expected Behavior (Mandatory)
add the plugin apoc 3.4.0.5 in /var/lib/neo4j/plugins in the docker container neo4j:3.4
run the neo4j container successfully.

## Actual Behavior (Mandatory)
when starting the container:
2019-04-16 07:47:40.363+0000 INFO  ======== Neo4j 3.4.12 ========
2019-04-16 07:47:40.420+0000 INFO  Starting...
2019-04-16 07:47:45.343+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2019-04-16 07:47:45.932+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@cb03411' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.Group". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@cb03411' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.scheduler.Group".

        ... 3 more
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: Lorg/neo4j/scheduler/Group;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredFields(Class.java:1916)

        ... 11 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.scheduler.Group
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 21 more

## How to Reproduce the Problem
create a dockerfile as follow

FROM neo4j:3.4
COPY apoc-3.4.0.5-all.jar /plugins/
CMD ["neo4j"]

run the container

### Versions

  - OS: docker neo4j
  - Neo4j: 3.4
  - Neo4j-Apoc: 3.4.0.5

**Comment by thomasricaud** [comment]
My bad i wasn't using the fat jar but downloading from maven repository the 			<groupId>org.neo4j.procedure</groupId>
			<artifactId>apoc</artifactId>
			<version>3.4.0.5</version>
by switching to the download url from github it works fine.
