### ISSUE TITLE
Neo4j 3.5.6 Failed to start on Windows 10

### ISSUE THREAD

**Issue by ilmimris** [neo4j-contrib/neo4j-apoc-procedures#1263]
## Expected Behavior (Mandatory)
Neo4j running.

## Actual Behavior (Mandatory)
Neo4j failed to start

## Log

```
2019-07-24 10:56:28.157+0000 INFO  ======== Neo4j 3.5.6 ========
2019-07-24 10:56:28.178+0000 INFO  Starting...
2019-07-24 10:56:35.156+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6d001fbe' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6d001fbe' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6d001fbe' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.BlockingBootstrapper.start(BlockingBootstrapper.java:41)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.CommunityEntryPoint.start(CommunityEntryPoint.java:46)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6d001fbe' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 4 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, E:\software\neo4j\data\databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
	at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 6 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@7cd1ec54' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
	... 10 more
Caused by: java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:161)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:138)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:111)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:85)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:323)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 12 more
```
## Config `neo4j.conf`
```
...
dbms.security.procedures.unrestricted=apoc.*
dbms.security.procedures.whitelist=apoc.coll.*,apoc.load.*,graphql.*
...
```

### Versions

  - OS: Windows 10
  - Neo4j: 3.5.6
  - Neo4j-Apoc: 3.5.0.4

**Comment by sarmbruster** [comment]
Any other libraries aside from apoc in your plugins folder?
There was an issue with graphaware plugins in the past, see https://github.com/graphaware/neo4j-framework/issues/83

**Comment by ilmimris** [comment]
> Any other libraries aside from apoc in your plugins folder?
> There was an issue with graphaware plugins in the past, see [graphaware/neo4j-framework#83](https://github.com/graphaware/neo4j-framework/issues/83)

Yes, only Graphql plugin. Is that problem?

**Comment by wrdls** [comment]
Getting the same error on Kubernetes with the Neo4j [helm chart](https://github.com/helm/charts/tree/master/stable/neo4j). No other plugins.

Neo4j: `3.5.6`
apoc:  `3.5.0.4`

**Comment by conker84** [comment]
fixed in newer versions
