### ISSUE TITLE
Terminating transactions that run `apoc.periodic.iterate(..., {parallel:true})` can cause database kernel panics.

### ISSUE THREAD

**Issue by chrisvest** [neo4j-contrib/neo4j-apoc-procedures#1314]
## Expected Behavior (Mandatory)

Terminating a transaction that is running `apoc.periodic.iterate(..., {parallel: true})` should distribute the _termination_ to its inner parallel transactions, and signal them to stop iterating.

## Actual Behavior (Mandatory)

The inner transactions are instead stopped via thread interrupt, through the `Util.getFutureOrCancel` function, which in turn calls `Future.cancel(true)`. The `true` argument to `Future` tells it to interrupt the thread working on the future.
This is bad because the Neo4j database internals are not interrupt-safe. One way this can go wrong, is if the transaction is in the middle of committing. In that case, the file channel for the transaction log can end up being `ClosedByInterruptException`. This compromises the crash-safety of the database, because the log was in such a case not forced prior to being closed.

## How to Reproduce the Problem

Run lots of parallel iterations of some write query, and then terminate the transaction before it can finish.

The bug will manifest itself as a stack trace printed to the debug log, and the database becoming unresponsive.

### Versions

  - OS: All.
  - Neo4j: There are no interrupt-safe Neo4j versions.
  - Neo4j-Apoc: All versions where `Util.getFutureOrCancel` is implemented the way it is.

**Comment by sarmbruster** [comment]
### To reproduce the issue prepopulate a empty db using:

```
call apoc.periodic.iterate(
"unwind range(1,10000000)  as i return i",
"create (p:Person{name:'person_' + i})",
{batchsize:10000, parallel:true})
```

Once finished this one:
```
call apoc.periodic.iterate(
"match (p:Person) return p",
"set p.name = p.name + 'ABCDEFGH'",
{batchsize:1, parallel:true, concurrency:20});
```

While running, get the queryId of that statement using
```
call dbms.listQueries() yield queryId, query, startTime
```

and kill it using 
```
call dbms.killQuery(<queryId>)
```

Any subsequent statement will fail until a restart of the db.

`debug.log`  shows up this:
```
2019-10-08 09:01:44.434+0000 ERROR [o.n.k.i.DatabaseHealth] Database panic: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
	at org.neo4j.io.fs.StoreFileChannel.write(StoreFileChannel.java:160)
	at org.neo4j.io.fs.StoreFileChannel.writeAll(StoreFileChannel.java:73)
	at org.neo4j.kernel.impl.transaction.log.PhysicalLogVersionedStoreChannel.writeAll(PhysicalLogVersionedStoreChannel.java:67)
	at org.neo4j.kernel.impl.transaction.log.PhysicalFlushableChannel.prepareForFlush(PhysicalFlushableChannel.java:72)
	at org.neo4j.kernel.impl.transaction.log.PhysicalFlushableChannel.bufferWithGuaranteedSpace(PhysicalFlushableChannel.java:158)
	at org.neo4j.kernel.impl.transaction.log.PhysicalFlushableChannel.putLong(PhysicalFlushableChannel.java:121)
	at org.neo4j.kernel.impl.transaction.log.PhysicalFlushableChannel.putLong(PhysicalFlushableChannel.java:36)
	at org.neo4j.kernel.impl.transaction.command.Command$PropertyCommand.writePropertyRecord(Command.java:424)
	at org.neo4j.kernel.impl.transaction.command.Command$PropertyCommand.serialize(Command.java:411)
	at org.neo4j.kernel.impl.transaction.log.entry.StorageCommandSerializer.visit(StorageCommandSerializer.java:43)
	at org.neo4j.kernel.impl.transaction.log.entry.StorageCommandSerializer.visit(StorageCommandSerializer.java:30)
	at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:70)
	at org.neo4j.kernel.impl.transaction.log.entry.LogEntryWriter.serialize(LogEntryWriter.java:84)
	at org.neo4j.kernel.impl.transaction.log.TransactionLogWriter.append(TransactionLogWriter.java:43)
	at org.neo4j.kernel.impl.transaction.log.BatchingTransactionAppender.appendToLog(BatchingTransactionAppender.java:211)
	at org.neo4j.kernel.impl.transaction.log.BatchingTransactionAppender.append(BatchingTransactionAppender.java:119)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.appendToLog(TransactionRepresentationCommitProcess.java:64)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:48)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:724)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:594)
	at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:178)
	at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:77)
	at apoc.util.Util.lambda$inTxFuture$4(Util.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
