### ISSUE TITLE
APOC load xls range problem with columns after Z

### ISSUE THREAD

**Issue by ThomasFrisendal** [neo4j-contrib/neo4j-apoc-procedures#1342]
I am trying to use apoc.load.xls to import from a large spreadsheet. It seems as if the range has to be between A and Z. But this spreadsheet goes all the way to AY.
Here is an example that works:

CALL apoc.load.xls('GQL_Inputs_and_comparative_analysis-2019-11-07.xlsx', '1.1 Basic operations!A1:Z10') yield lineNo, list
return *

And here is an example that does not work:

CALL apoc.load.xls('GQL_Inputs_and_comparative_analysis-2019-11-07.xlsx', '1.1 Basic operations!A1:AY10') yield lineNo, list
return *

Error message: 

Failed to invoke procedure `apoc.load.xls`: Caused by: java.lang.IllegalStateException: Header at position 51 doesn't have a value

See screendumps here: https://community.neo4j.com/t/apoc-load-xls-range-problem-with-columns-after-z/11782?u=thomasf

Neo4j Browser version: 3.2.24

Neo4j Server version: 3.5.8 (enterprise)

The Apache libraries were downloaded a couple of weeks ago.

The spreadsheet can be found here: https://docs.google.com/spreadsheets/d/1zpLDPWQYwACgphPz8MxcKvtbOjF3Ye-z5d2jSnNa1GI/edit#gid=1358645973

Best regards

Thomas

**Comment by conker84** [comment]
[apoc-3.5.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3845817/apoc-3.5.0.5-all.jar.zip)

Hi @ThomasFrisendal can you try with the jar above?
I'm look forward to your feedback!
Thanks a lot!

**Comment by ThomasFrisendal** [comment]
Hi @conker84 - so you want me to replace apoc-3.5.0.4.jar with the new one?

**Comment by conker84** [comment]
Yes please

**Comment by ThomasFrisendal** [comment]
2019-11-14 10:37:10.869+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@c2c1622' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@c2c1622' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@c2c1622' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@c2c1622' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@79309b5c' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.metrics.get` is already in use.
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:87)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:138)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:93)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:326)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2019-11-14 10:37:10.871+0000 INFO  Neo4j Server shutdown initiated by request
Active database: graph.db
Directories in use:
  home:         /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8
  config:       /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/conf
  logs:         /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/logs
  plugins:      /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/plugins
  import:       /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/import
  data:         /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/data
  certificates: /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/certificates
  run:          /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/run
Starting Neo4j.
2019-11-14 10:38:17.155+0000 INFO  ======== Neo4j 3.5.8 ========
2019-11-14 10:38:17.188+0000 INFO  Starting...
2019-11-14 10:38:24.013+0000 INFO  Initiating metrics...
2019-11-14 10:38:43.700+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3683407d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3683407d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3683407d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3683407d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/Thomas/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-657734cd-ecc4-4d5b-93e1-74963ad6239a/installation-3.5.8/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@14d21cb9' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.metrics.get` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
	... 9 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.metrics.get` is already in use.
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:87)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:138)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:93)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:326)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2019-11-14 10:38:43.703+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by ThomasFrisendal** [comment]
![image](https://user-images.githubusercontent.com/12172003/68850175-c8813b00-06d3-11ea-8268-f30737571ecb.png)

**Comment by conker84** [comment]
Follow these steps:
1. stop the db
2. move the old jar into another dir outside the `plugin` dir
3. start the db

**Comment by ThomasFrisendal** [comment]
That certainly helped. Grazie!

**Comment by conker84** [comment]
Prego!:grin:
