### ISSUE TITLE
java.lang.IllegalStateException: Transaction id is not assigned yet. It will be assigned during transaction commit.

### ISSUE THREAD

**Issue by jphoulchand** [neo4j-contrib/neo4j-apoc-procedures#1343]
Customer is having the error:
`java.lang.IllegalStateException: Transaction id is not assigned yet. It will be assigned during transaction commit.`

## Expected Behavior (Mandatory)
No errors

## Actual Behavior (Mandatory)
2019-11-07 11:27:24.127+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Transaction id is not assigned yet. It will be assigned during transaction commit., reference 5482e046-a290-4955-a7df-b284d81a3eeb. Transaction id is not assigned yet. It will be assigned during transaction commit.
java.lang.IllegalStateException: Transaction id is not assigned yet. It will be assigned during transaction commit.
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.getTransactionId(KernelTransactionImplementation.java:1042)
        at org.neo4j.kernel.impl.coreapi.TxStateTransactionDataSnapshot.getTransactionId(TxStateTransactionDataSnapshot.java:189)
        at apoc.trigger.Trigger.txDataParams(Trigger.java:316)
        at apoc.trigger.Trigger.access$000(Trigger.java:29)
        at apoc.trigger.Trigger$TriggerHandler.executeTriggers(Trigger.java:271)
        at apoc.trigger.Trigger$TriggerHandler.afterCommit(Trigger.java:305)
        at org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:149)
        at org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:48)
        at org.neo4j.kernel.impl.api.TransactionHooks.afterCommit(TransactionHooks.java:76)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.afterCommit(KernelTransactionImplementation.java:921)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:744)
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:594)
        at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:178)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:469)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.commitTransaction(TransactionStateMachine.java:402)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.commitTransaction(TransactionStateMachine.java:144)
        at org.neo4j.bolt.v3.runtime.TransactionReadyState.processCommitMessage(TransactionReadyState.java:93)
        at org.neo4j.bolt.v3.runtime.TransactionReadyState.processUnsafe(TransactionReadyState.java:53)
        at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
        at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
        at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
        at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnec

### Steps (Mandatory)

1) customer enabled `apoc.trigger.enabled=true` in neo4j.conf

2) The following scenario is executed:

```
neo4j> :begin
neo4j# CREATE (n:Test{id:'100'});
neo4j# MATCH (n:Test) DELETE n;
neo4j# :commit
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux Redhat, macOS
  - Neo4j:3.5.11
  - Neo4j-Apoc:3.5.11

**Comment by barakharizima** [comment]
Experiencing the same, also using APOC triggers
@jphoulchand did you manage to resolve it?

**Comment by sarmbruster** [comment]
it seems you have an after trigger in place. What statement are you running there?

**Comment by barakharizima** [comment]
Hey @sarmbruster,
I am running the following:
```CALL apoc.trigger.add('created-at-timestamp','UNWIND $createdNodes AS node SET node.createdAt = timestamp()', {phase:'before'});```

**Comment by barakharizima** [comment]
This is what I'm seeing in the debug logs:
```Caused by: java.lang.IllegalStateException: Transaction commit time is not assigned yet. It will be assigned during transaction commit.
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.getCommitTime(KernelTransactionImplementation.java:1083)
	at org.neo4j.kernel.internal.event.TxStateTransactionDataSnapshot.getCommitTime(TxStateTransactionDataSnapshot.java:196)
	at apoc.trigger.TriggerHandler.txDataParams(TriggerHandler.java:239)
	at apoc.trigger.TriggerHandler.executeTriggers(TriggerHandler.java:254)
	at apoc.trigger.TriggerHandler.afterCommit(TriggerHandler.java:193)
	at apoc.trigger.TriggerHandler.afterCommit(TriggerHandler.java:41)
	at org.neo4j.kernel.internal.event.DatabaseTransactionEventListeners.afterCommit(DatabaseTransactionEventListeners.java:99)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.afterCommit(KernelTransactionImplementation.java:973)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commitTransaction(KernelTransactionImplementation.java:781)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:635)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:602)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.safeTerminalOperation(TransactionImpl.java:510)```

**Comment by jphoulchand** [comment]
This works fine in 4.2. Closing.
