### ISSUE TITLE
Neo4j 4.0.0 and APOC release 4.0.0.2 appear incompatible

### ISSUE THREAD

**Issue by cooperfrench95** [neo4j-contrib/neo4j-apoc-procedures#1395]
## Expected Behavior (Mandatory)

Installing neo4j and placing APOC jar file in plugins directory allows neo4j to start and makes APOC features available

## Actual Behavior (Mandatory)

Neo4j will not start.

### Steps (Mandatory)

  1. Install neo4j 4.0.0 using the instructions found at https://neo4j.com/docs/operations-manual/current/installation/linux/debian/#debian-installation
  2. Download jar file:
     `sudo curl https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.0.0.2/apoc-4.0.0.2-all.jar > /var/lib/neo4j/plugins/apoc-4.0.0.2-all.jar`
  3. Try to start neo4j. Neo4j fails to start, check logs.

### Logs

```
nohup: ignoring input
2020-01-31 18:29:21.869+0000 WARN  Use of deprecated setting dbms.directories.certificates. Legacy ssl policy is no longer supported.
2020-01-31 18:29:21.889+0000 INFO  ======== Neo4j 4.0.0 ========
2020-01-31 18:29:21.893+0000 INFO  Starting...
2020-01-31 18:29:31.423+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@7efa3f63' was successfully initialized, but failed to start. Please see the attached cause exception "Some jar procedure files are invalid, see log for details.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@7efa3f63' was successfully initialized, but failed to start. Please see the attached cause exception "Some jar procedure files are invalid, see log for details.".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@7efa3f63' was successfully initialized, but failed to start. Please see the attached cause exception "Some jar procedure files are invalid, see log for details.".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:163)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:114)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:25)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@7efa3f63' was successfully initialized, but failed to start. Please see the attached cause exception "Some jar procedure files are invalid, see log for details.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:465)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:156)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting database server at /var/lib/neo4j/data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:167)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:145)
	at com.neo4j.server.database.EnterpriseGraphFactory.newDatabaseManagementService(EnterpriseGraphFactory.java:38)
	at org.neo4j.server.database.LifecycleManagingDatabaseService.start(LifecycleManagingDatabaseService.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@222afc67' was successfully initialized, but failed to start. Please see the attached cause exception "Some jar procedure files are invalid, see log for details.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:465)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:158)
	... 9 more
Caused by: java.util.zip.ZipException: Some jar procedure files are invalid, see log for details.
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:76)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:342)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	... 11 more
2020-01-31 18:29:31.427+0000 INFO  Neo4j Server shutdown initiated by request

```

## Specifications (Mandatory)

32gb ram, 3rd-gen i5

### Versions

  - OS: Ubuntu 18.04
  - Neo4j: 4.0.0 (Enterprise)
  - Neo4j-Apoc: 4.0.0.2

**Comment by jexp** [comment]
Use curl -OL and not a redirect
Or -o

Otherwise it garbles the progress output into the file

**Comment by cooperfrench95** [comment]
@jexp Same result using the -o option. Neo4j still won't start.

**Comment by cooperfrench95** [comment]
Additionally, neo4j works fine when I remove apoc

**Comment by cooperfrench95** [comment]
Well, I'm an idiot.

Thought @jexp meant `>` by redirect, turns out the link to that file returns a redirect HTML page and this is what curl placed inside the apoc file.
