### ISSUE TITLE
Stuck in loading cypher procedures

### ISSUE THREAD

**Issue by Roxling** [neo4j-contrib/neo4j-apoc-procedures#1398]
## Expected Behavior
Apoc does not affect server shutdown time when not used

## Actual Behavior
Adding Apoc as maven dependency adds ~10s to shutdown

## How to Reproduce the Problem
Add
```        
<dependency>
            <groupId>org.neo4j.procedure</groupId>
            <artifactId>apoc</artifactId>
            <version>4.0.0.2</version>
            <scope>test</scope>
</dependency>
```
And run
```
Neo4jBuilders.newInProcessBuilder().build().close();
```
With Apoc this takes around 10s longer than without Apoc dependency.

Server is stuck here:
```
98.83%: app//org.neo4j.dbms.database.AbstractDatabaseManager.stopDatabase(AbstractDatabaseManager.java:201)
94.32%: app//org.neo4j.kernel.database.Database.stop(Database.java:721)
    94.32%: app//org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:147)
    94.32%: app//org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:261)
        94.32%: app//org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:479)
        94.13%: app//org.neo4j.kernel.availability.DatabaseAvailability.stop(DatabaseAvailability.java:72)
            93.93%: app//org.neo4j.kernel.availability.DatabaseAvailability.awaitTransactionsClosedWithinTimeout(DatabaseAvailability.java:80)
            93.93%: java.base@11.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
                93.93%: java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
```
With an Apoc thread stuck here:
```
	at java.base@11.0.2/java.lang.Thread.sleep(Native Method)
	at app//apoc.cypher.CypherInitializer.awaitApocProceduresRegistered(CypherInitializer.java:76)
	at app//apoc.cypher.CypherInitializer.lambda$available$3(CypherInitializer.java:48)
	at app//apoc.cypher.CypherInitializer$$Lambda$2415/0x0000000100cc0c40.run(Unknown Source)
	at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)
```

### Simple Dataset (where it's possibile)
Empty database
### Versions
  - OS: Ubuntu 18.04
  - Neo4j: 4.0
  - Neo4j-Apoc: 4.0.0.2

**Comment by jexp** [comment]
It would be good if this was fixed in the product.
But yes we should fix this particular wait.
Weird that it waits on shutdown, it's only called on "available"

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.5/src/main/java/apoc/cypher/CypherInitializer.java#L37-L39

**Comment by sarmbruster** [comment]
Just verified that a shutdown on 4.0 EE takes ~7 s without and ~17s with apoc on board.

**Comment by sarmbruster** [comment]
However CypherInitializer.available() is *not* called during shutdown. @Roxling can you verify that the 2nd trace is from a shutdown sequence?

**Comment by Roxling** [comment]
@sarmbruster 
The 2nd trace is from a leaked thread making no progress for >90s after server is shut down. That thread should be killed on a shutdown path if it's still running, not just left as is. My guess is that it is  keeping some transaction open, causing the kernel to wait for it to close on shutdown.

**Comment by lszumel** [comment]
I am a similar issue under Neo4j 3.5.14, except the JVM *never* exits and it appears to be due to this step. Is that a unique issue or the same issue? Here are the non-daemon threads in the stack dump from the hanged JVM:
```
"DestroyJavaVM" #132 prio=5 os_prio=0 tid=0x00007fa43000a800 nid=0x41c14 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-6" #38 prio=5 os_prio=0 tid=0x00007fa43096f000 nid=0x435be waiting on condition [0x00007fa38adf6000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at apoc.cypher.CypherInitializer.awaitApocProceduresRegistered(CypherInitializer.java:72)
	at apoc.cypher.CypherInitializer.lambda$available$0(CypherInitializer.java:43)
	at apoc.cypher.CypherInitializer$$Lambda$449/698977695.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"VM Thread" os_prio=0 tid=0x00007fa4300c1800 nid=0x41c7f runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fa430020000 nid=0x41c27 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fa430022000 nid=0x41c28 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fa430023800 nid=0x41c29 runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fa430025000 nid=0x41c2a runnable

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007fa430027000 nid=0x41c2b runnable

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007fa430028800 nid=0x41c2c runnable

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007fa43002a800 nid=0x41c2d runnable

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007fa43002c000 nid=0x41c2f runnable

"GC task thread#8 (ParallelGC)" os_prio=0 tid=0x00007fa43002e000 nid=0x41c30 runnable

"GC task thread#9 (ParallelGC)" os_prio=0 tid=0x00007fa43002f800 nid=0x41c31 runnable

"GC task thread#10 (ParallelGC)" os_prio=0 tid=0x00007fa430031800 nid=0x41c32 runnable

"GC task thread#11 (ParallelGC)" os_prio=0 tid=0x00007fa430033000 nid=0x41c34 runnable

"GC task thread#12 (ParallelGC)" os_prio=0 tid=0x00007fa430035000 nid=0x41c35 runnable

"GC task thread#13 (ParallelGC)" os_prio=0 tid=0x00007fa430036800 nid=0x41c36 runnable

"GC task thread#14 (ParallelGC)" os_prio=0 tid=0x00007fa430038800 nid=0x41c37 runnable

"GC task thread#15 (ParallelGC)" os_prio=0 tid=0x00007fa43003a000 nid=0x41c39 runnable

"GC task thread#16 (ParallelGC)" os_prio=0 tid=0x00007fa43003c000 nid=0x41c3a runnable

"GC task thread#17 (ParallelGC)" os_prio=0 tid=0x00007fa43003d800 nid=0x41c3b runnable

"GC task thread#18 (ParallelGC)" os_prio=0 tid=0x00007fa43003f800 nid=0x41c3c runnable

"GC task thread#19 (ParallelGC)" os_prio=0 tid=0x00007fa430041000 nid=0x41c3d runnable

"GC task thread#20 (ParallelGC)" os_prio=0 tid=0x00007fa430043000 nid=0x41c3e runnable

"GC task thread#21 (ParallelGC)" os_prio=0 tid=0x00007fa430044800 nid=0x41c3f runnable

"GC task thread#22 (ParallelGC)" os_prio=0 tid=0x00007fa430046800 nid=0x41c40 runnable

"GC task thread#23 (ParallelGC)" os_prio=0 tid=0x00007fa430048000 nid=0x41c41 runnable

"GC task thread#24 (ParallelGC)" os_prio=0 tid=0x00007fa43004a000 nid=0x41c42 runnable

"GC task thread#25 (ParallelGC)" os_prio=0 tid=0x00007fa43004b800 nid=0x41c44 runnable

"GC task thread#26 (ParallelGC)" os_prio=0 tid=0x00007fa43004d800 nid=0x41c45 runnable

"GC task thread#27 (ParallelGC)" os_prio=0 tid=0x00007fa43004f000 nid=0x41c46 runnable

"GC task thread#28 (ParallelGC)" os_prio=0 tid=0x00007fa430051000 nid=0x41c47 runnable

"GC task thread#29 (ParallelGC)" os_prio=0 tid=0x00007fa430052800 nid=0x41c48 runnable

"GC task thread#30 (ParallelGC)" os_prio=0 tid=0x00007fa430054800 nid=0x41c49 runnable

"GC task thread#31 (ParallelGC)" os_prio=0 tid=0x00007fa430056000 nid=0x41c4a runnable

"GC task thread#32 (ParallelGC)" os_prio=0 tid=0x00007fa430058000 nid=0x41c4b runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007fa430137000 nid=0x41cfc waiting on condition
```
As you can see there doesn't seem to be anything going on except for `apoc.cypher.CypherInitializer.awaitApocProceduresRegistered()`

**Comment by jexp** [comment]
@sarmbruster do you want to look into this one? 
All apoc threads should be daemon threads.
