### ISSUE TITLE
Registering procedures on startup fails on a read replica

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1413]
# Expected Behavior (Mandatory)

Using Neo4j 4.0 with apoc 4.0.0.1, in a causal cluster configuration with 3 core, 1 RR all running in docker-compose.  A previously registered procedure comes alive when the cluster starts on all nodes except the read replica.

Expected behavior is for the read-only procedure to come alive.

## Actual Behavior (Mandatory)

```
read1_1  | 2020-02-17 20:02:08.542+0000 ERROR [demodb] Could not register procedure: custom.isDatabaseOnline with CALL apoc.systemdb.execute("SHOW DATABASES")
read1_1  |    YIELD row WITH row.name as name, row.currentStatus as status
read1_1  |    WHERE name = $name
read1_1  |    WITH collect(distinct(status)) as statuses
read1_1  |    RETURN (size(statuses) = 1 AND statuses[0] = "online") as online;
read1_1  |  accepting[name :: STRING?] resulting in [online :: BOOLEAN?] mode READ
read1_1  | java.lang.UnsupportedOperationException
read1_1  | 	at java.base/java.util.AbstractCollection.add(AbstractCollection.java:267)
read1_1  | 	at apoc.custom.CypherProceduresHandler.registerProcedure(CypherProceduresHandler.java:319)
read1_1  | 	at apoc.custom.CypherProceduresHandler$ProcedureDescriptor.register(CypherProceduresHandler.java:616)
read1_1  | 	at apoc.custom.CypherProceduresHandler.lambda$restoreProceduresAndFunctions$2(CypherProceduresHandler.java:168)
read1_1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
read1_1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
read1_1  | 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
read1_1  | 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
read1_1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
read1_1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
read1_1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
read1_1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
read1_1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
read1_1  | 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
read1_1  | 	at apoc.custom.CypherProceduresHandler.restoreProceduresAndFunctions(CypherProceduresHandler.java:167)
read1_1  | 	at apoc.custom.CypherProceduresHandler.available(CypherProceduresHandler.java:81)
read1_1  | 	at org.neo4j.internal.helpers.Listeners.notifySingleListener(Listeners.java:126)
read1_1  | 	at org.neo4j.internal.helpers.Listeners.notify(Listeners.java:83)
read1_1  | 	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:119)
read1_1  | 	at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:61)
read1_1  | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
read1_1  | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
read1_1  | 	at org.neo4j.kernel.database.Database.start(Database.java:462)
read1_1  | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
read1_1  | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
read1_1  | 	at com.neo4j.causalclustering.common.ClusteredDatabase.start(ClusteredDatabase.java:39)
read1_1  | 	at com.neo4j.dbms.database.ClusteredMultiDatabaseManager.startDatabase(ClusteredMultiDatabaseManager.java:79)
read1_1  | 	at com.neo4j.dbms.database.ClusteredMultiDatabaseManager.startDatabase(ClusteredMultiDatabaseManager.java:37)
read1_1  | 	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:112)
read1_1  | 	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:98)
read1_1  | 	at com.neo4j.dbms.DbmsReconciler.start(DbmsReconciler.java:537)
read1_1  | 	at com.neo4j.dbms.Transitions$TransitionFunction.lambda$prepare$0(Transitions.java:219)
read1_1  | 	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:335)
read1_1  | 	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:336)
read1_1  | 	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:318)
read1_1  | 	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$9(DbmsReconciler.java:308)
read1_1  | 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
read1_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
read1_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
read1_1  | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

## How to Reproduce the Problem

Create a causal cluster with a read replica.  Register a procedure.  Shut down the entire cluster and restart.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

**Comment by conker84** [comment]
this should be fixed in newer versions
