### ISSUE TITLE
Error "CALL dbms.cluster.role()"

### ISSUE THREAD

**Issue by saurabh-opoyi** [neo4j-contrib/neo4j-apoc-procedures#1550]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
CALL dbms.cluster.role('neo4j')

## Actual Behavior (Mandatory)
CALL dbms.cluster.role()

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:  Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1019-aws x86_64)
  - Neo4j: Neo4j 4.0.4 (Enterprise Cluster)
  - Neo4j-Apoc: 4.0.0.13

org.neo4j.graphdb.QueryExecutionException: Procedure call does not provide the required number of arguments: got 0 expected at least 1 (total: 1, 0 of which have default values).

Procedure dbms.cluster.role has signature: dbms.cluster.role(database :: STRING?) :: role :: STRING?
meaning that it expects at least 1 argument of type STRING?
Description: The role of this instance in the cluster for the specified database. (line 1, column 1 (offset: 0))
"CALL dbms.cluster.role()"
 ^
	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:236)
	at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:217)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.executeTransactionally(GraphDatabaseFacade.java:154)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.executeTransactionally(GraphDatabaseFacade.java:144)
	at apoc.util.Util.isWriteableInstance(Util.java:696)
	at apoc.ttl.TTLLifeCycle.expireNodes(TTLLifeCycle.java:51)
	at apoc.ttl.TTLLifeCycle.lambda$start$0(TTLLifeCycle.java:45)
	at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:87)
	at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:73)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Procedure call does not provide the required number of arguments: got 0 expected at least 1 (total: 1, 0 of which have default values).

**Comment by conker84** [comment]
Fixed
