### ISSUE TITLE
Create TTL only if it doesn't exist

### ISSUE THREAD

**Issue by gwvandesteeg** [neo4j-contrib/neo4j-apoc-procedures#1603]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/16581f3253f82e75506428dfd2a498346c6bfb1d/full/src/main/java/apoc/ttl/TTLLifeCycle.java#L69

The TTL index should be amended to be IF NOT EXISTS, otherwise you get a nice exception on startup, however this will limit it to versions of neo4j which support the IF NOT EXISTS on index/constraint creation.

```neo4j_1                    | 2020-07-28 23:40:06.847+0000 ERROR [neo4j] TTL: Error creating index An equivalent index already exists, 'Index( 1, 'index_a5e3e466', GENERAL BTREE, :TTL(ttl), native-btree-1.0 )'.
neo4j_1                    | org.neo4j.graphdb.QueryExecutionException: An equivalent index already exists, 'Index( 1, 'index_a5e3e466', GENERAL BTREE, :TTL(ttl), native-btree-1.0 )'.
neo4j_1                    |    at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
neo4j_1                    |    at org.neo4j.cypher.internal.javacompat.ResultSubscriber.converted(ResultSubscriber.java:412)
neo4j_1                    |    at org.neo4j.cypher.internal.javacompat.ResultSubscriber.assertNoErrors(ResultSubscriber.java:393)
neo4j_1                    |    at org.neo4j.cypher.internal.javacompat.ResultSubscriber.init(ResultSubscriber.java:80)
neo4j_1                    |    at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:111)
neo4j_1                    |    at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:228)
neo4j_1                    |    at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:217)
neo4j_1                    |    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.executeTransactionally(GraphDatabaseFacade.java:154)
neo4j_1                    |    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.executeTransactionally(GraphDatabaseFacade.java:144)
neo4j_1                    |    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.executeTransactionally(GraphDatabaseFacade.java:132)
neo4j_1                    |    at apoc.ttl.TTLLifeCycle.createTTLIndex(TTLLifeCycle.java:68)
neo4j_1                    |    at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:87)
neo4j_1                    |    at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:73)
neo4j_1                    |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
neo4j_1                    |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
neo4j_1                    |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
neo4j_1                    |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
neo4j_1                    |    at java.base/java.lang.Thread.run(Thread.java:834)
neo4j_1                    | Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: An equivalent index already exists, 'Index( 1, 'index_a5e3e466', GENERAL BTREE, :TTL(ttl), native-btree-1.0 )'.
neo4j_1                    |    ... 17 more
neo4j_1                    | Caused by: org.neo4j.exceptions.CypherExecutionException: An equivalent index already exists, 'Index( 1, 'index_a5e3e466', GENERAL BTREE, :TTL(ttl), native-btree-1.0 )'.
neo4j_1                    |    at org.neo4j.cypher.internal.planning.ExceptionTranslationSupport.translateException(ExceptionTranslationSupport.scala:41)
neo4j_1                    |    at org.neo4j.cypher.internal.planning.ExceptionTranslationSupport.translateException$(ExceptionTranslationSupport.scala:32)
neo4j_1                    |    at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:40)
neo4j_1                    |    at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.addIndexRule(ExceptionTranslatingQueryContext.scala:101)
neo4j_1                    |    at org.neo4j.cypher.internal.runtime.interpreted.UpdateCountingQueryContext.addIndexRule(UpdateCountingQueryContext.scala:106)
neo4j_1                    |    at org.neo4j.cypher.internal.SchemaCommandRuntime$$anonfun$1.$anonfun$applyOrElse$28(SchemaCommandRuntime.scala:122)
neo4j_1                    |    at org.neo4j.cypher.internal.SchemaCommandRuntime$$anonfun$1.$anonfun$applyOrElse$28$adapted(SchemaCommandRuntime.scala:119)
neo4j_1                    |    at org.neo4j.cypher.internal.procs.SchemaWriteExecutionPlan.run(SchemaWriteExecutionPlan.scala:50)
neo4j_1                    |    at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.innerExecute(CypherCurrentCompiler.scala:302)
neo4j_1                    |    at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:264)
neo4j_1                    |    at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:230)
neo4j_1                    |    at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubQuery$1(ExecutionEngine.scala:190)
neo4j_1                    |    at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:195)
neo4j_1                    |    at org.neo4j.cypher.internal.ExecutionEngine.executeSubQuery(ExecutionEngine.scala:188)
neo4j_1                    |    at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:139)
neo4j_1                    |    at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:121)
neo4j_1                    |    at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:110)
neo4j_1                    |    ... 13 more
neo4j_1                    | Caused by: org.neo4j.kernel.api.exceptions.schema.EquivalentSchemaRuleAlreadyExistsException: An equivalent index already exists, 'Index( 1, 'index_a5e3e466', GENERAL BTREE, :TTL(ttl), native-btree-1.0 )'.
neo4j_1                    |    at org.neo4j.kernel.impl.newapi.Operations.assertNoBlockingSchemaRulesExists(Operations.java:1033)
neo4j_1                    |    at org.neo4j.kernel.impl.newapi.Operations.indexCreate(Operations.java:810)
neo4j_1                    |    at org.neo4j.kernel.impl.newapi.Operations.indexCreate(Operations.java:826)
neo4j_1                    |    at org.neo4j.kernel.impl.newapi.Operations.indexCreate(Operations.java:818)
neo4j_1                    |    at org.neo4j.kernel.impl.api.RestrictedSchemaWrite.indexCreate(RestrictedSchemaWrite.java:76)
neo4j_1                    |    at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.addIndexRule(TransactionBoundQueryContext.scala:689)
neo4j_1                    |    at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.$anonfun$addIndexRule$1(ExceptionTranslatingQueryContext.scala:101)
neo4j_1                    |    at org.neo4j.cypher.internal.planning.ExceptionTranslationSupport.translateException(ExceptionTranslationSupport.scala:33)
neo4j_1                    |    ... 29 more
```

**Comment by gwvandesteeg** [comment]
Duplicate
