### ISSUE TITLE
Failed to invoke procedure `apoc.load.driver - Caused by: org.postgresql.util.PSQLException

### ISSUE THREAD

**Issue by bandaja** [neo4j-contrib/neo4j-apoc-procedures#1655]
Steps (Mandatory)

1.	Download the JDBC for postgresql:
https://jdbc.postgresql.org/   --> postgresql-42.2.16

2.	Download the APOC Full JAR from:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.1.0.2  --> apoc-4.1.0.2-all

3.	Put "apoc-4.1.0.2-all " and JDBC Driver into my "plugins":
$NEO4J_HOME\plugins\

4.	Restart the services.

5.	run the query:
CALL apoc.load.jdbc('jdbc:postgresql://localhost:7474/mock?user=XXXX&password=XXXX', 'SELECT name FROM XXXX.state') YIELD row
CREATE (n:States {name:row.name})

6.	I got the error message:
Failed to invoke procedure `apoc.load.jdbc`: Caused by: org.postgresql.util.PSQLException: An error occurred while setting up the GSS Encoded connection.

Specifications (Mandatory)
Versions:

Neo4j: version: 4.1.1

Postgresql: Ver 12.3

OS: win10 64

Apoc: 4.1.0.2

Regards,
Francisco Javier Banda

**Comment by jexp** [comment]
Anything in the logs with more details on the exception?

**Comment by bandaja** [comment]
2020-09-06 19:52:30.200+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=108, gcTime=0, gcCount=0}
2020-09-06 19:56:09.090+0000 ERROR [o.n.k.a.p.GlobalProcedures] Cannot execute SQL statement `SELECT name FROM bandaja.state`.
Error:
An error occurred while setting up the GSS Encoded connection. An error occurred while setting up the GSS Encoded connection.
org.postgresql.util.PSQLException: An error occurred while setting up the GSS Encoded connection.
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableGSSEncrypted(ConnectionFactoryImpl.java:480)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:144)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.connect(Driver.java:264)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at apoc.load.util.JdbcUtil.getConnection(JdbcUtil.java:34)
	at apoc.load.Jdbc.executeQuery(Jdbc.java:82)
	at apoc.load.Jdbc.jdbc(Jdbc.java:66)
	at org.neo4j.kernel.impl.proc.GeneratedProcedure_jdbc1438082091011500.apply(Unknown Source)
	at org.neo4j.procedure.impl.ProcedureRegistry.callProcedure(ProcedureRegistry.java:208)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.callProcedure(GlobalProceduresRegistry.java:323)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:966)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallRead(AllStoreHolder.java:869)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.$anonfun$callReadOnlyProcedure$2(CallSupport.scala:51)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callProcedure(CallSupport.scala:98)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callReadOnlyProcedure(CallSupport.scala:53)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadOnlyProcedure(TransactionBoundQueryContext.scala:880)
	at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.callReadOnlyProcedure(ExceptionTranslatingQueryContext.scala:203)
	at org.neo4j.cypher.internal.runtime.interpreted.DelegatingQueryContext.callReadOnlyProcedure(DelegatingQueryContext.scala:283)
	at org.neo4j.cypher.internal.runtime.LazyReadOnlyCallMode.callProcedure(ProcedureCallMode.scala:52)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.call(ProcedureCallPipe.scala:87)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$1(ProcedureCallPipe.scala:73)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:70)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:66)
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:59)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:99)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.initiate(StandardInternalExecutionResult.scala:62)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.$anonfun$initiate$1(ClosingExecutionResult.scala:59)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.safely(ClosingExecutionResult.scala:100)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.initiate(ClosingExecutionResult.scala:59)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult$.wrapAndInitiate(ClosingExecutionResult.scala:189)
	at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.innerExecute(CypherCurrentCompiler.scala:354)
	at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:291)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:219)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$execute$1(ExecutionEngine.scala:151)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:185)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:151)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:135)
	at org.neo4j.fabric.executor.FabricKernelTransaction.lambda$execute$0(FabricKernelTransaction.java:91)
	at org.neo4j.fabric.stream.StatementResults.connectVia(StatementResults.java:56)
	at org.neo4j.fabric.executor.FabricKernelTransaction.run(FabricKernelTransaction.java:80)
	at org.neo4j.fabric.executor.FabricLocalExecutor$LocalTransactionContext.run(FabricLocalExecutor.java:93)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.runLocalQueryAt(FabricExecutor.java:374)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.runExec(FabricExecutor.java:343)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.run(FabricExecutor.java:282)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.run(FabricExecutor.java:251)
	at org.neo4j.fabric.executor.FabricExecutor.lambda$run$0(FabricExecutor.java:148)
	at org.neo4j.fabric.transaction.FabricTransactionImpl.execute(FabricTransactionImpl.java:307)
	at org.neo4j.fabric.executor.FabricExecutor.run(FabricExecutor.java:132)
	at org.neo4j.fabric.bolt.BoltFabricDatabaseService$BoltTransactionImpl.executeQuery(BoltFabricDatabaseService.java:165)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractTransactionStateMachineSPI$AbstractBoltResultHandle.start(AbstractTransactionStateMachineSPI.java:135)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:534)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State$2.run(TransactionStateMachine.java:330)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.run(TransactionStateMachine.java:84)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.run(TransactionStateMachine.java:77)
	at org.neo4j.bolt.v4.runtime.InTransactionState.processRunMessage(InTransactionState.java:81)
	at org.neo4j.bolt.v4.runtime.InTransactionState.processUnsafe(InTransactionState.java:48)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:143)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:91)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:90)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:148)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:237)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:172)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:162)
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:246)
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$3(ExecutorBoltScheduler.java:229)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by sarmbruster** [comment]
Maybe https://www.ibm.com/support/pages/ibm-datastage-jdbc-connector-test-connection-fails-orgpostgresqlutilpsqlexception helps? So please try

```
CALL apoc.load.jdbc('jdbc:postgresql://localhost:7474/mock?user=XXXX&password=XXXX&gssEncMode=disable', 'SELECT name FROM XXXX.state') YIELD row
CREATE (n:States {name:row.name})
```

**Comment by bandaja** [comment]
Thanks, I tried..

**Comment by bandaja** [comment]
As per Sarmbruster suggestion:
Answer
If encryption is not configured, should be disabled by setting JDBC connection parameter gssEncMode=disable.

Base on the information from this document, I can see the encryption is not configured in my Postgresql database:

PostgreSQL GSSAPI Authentication with Kerberos part-3: the status of authentication, encryption and user principal
https://www.highgo.ca/2020/03/30/postgresql-gssapi-authentication-with-kerberos-part-3-the-status-of-authentication-encryption-and-user-principal/

Both authentication and encryption are enabled when the host-based authentication is configured with hostgssenc and gss in ph_hba.conf:
# TYPE  DATABASE        		USER            	ADDRESS                 	METHOD

# "local" is for Unix domain socket connections only
local   		all             	all                                     peer
# IPv4 local connections:
host    		all             	all             	127.0.0.1/32            	md5
# IPv6 local connections:
host   		all             	all             	::1/128                 	md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   		replication     	all                                     			peer
host    		replication     	all             	127.0.0.1/32            	md5
host    		replication     	all             	::1/128                 	md5
host    		all             	all             	35.235.240.0/20          	md5

From the result of this query, we can see this connection is NOT encrypted:
mock=# SELECT pid, gss_authenticated, encrypted, principal from pg_stat_gssapi where pid = pg_backend_pid();
 pid    | gss_authenticated  | encrypted | principal
--------+--------------------------+---------------+-----------
 9971 | f                                 | f         |
(1 row)

The document also suggest, You can also achieve the same result by setting the environment PGGSSENCMODE=disable from the client side.


No sure, how to set the environment PGGSSENCMODE=disable, in other words, how to manually disable gssenc mode.

I tried...
CALL apoc.load.jdbc('jdbc:postgresql://localhost:7474/mock?PGGSSENCMODE=disable?user=bandaja&password=bandaja', 'SELECT name FROM bandaja.state') YIELD row
CREATE (n:States {name:row.name})
But, still the same error..
Failed to invoke procedure `apoc.load.jdbc`: Caused by: org.postgresql.util.PSQLException: An error occurred while setting up the GSS Encoded connection.


Then I tried…
CALL apoc.load.jdbc('jdbc:postgresql://localhost:7474/mock?user=bandaja&password=bandaja?PGGSSENCMODE=disable', 'SELECT name FROM bandaja.state) YIELD row
CREATE (n:States {name:row.name})
Then, I have a different error…
Unexpected end of input: expected '\', ANY or ''' (line 2, column 34 (offset: 188))
"CREATE (n:States {name:row.name})"

My question, can I use the environmental PGGSSENCMODE=disable from the procedure (apoc.load.jdbc)?

**Comment by sarmbruster** [comment]
So you basically want to have `PGGSSENCMODE=disable` as environment variable being set when Neo4j starts up, right?

I've checked the startup scripts on Neo4j 4.1.1 for Linux - they export any setting from `conf/neo4j.conf` as environment variable. Therefore it should be good enough to amend `PGGSSENCMODE=disable` to `conf/neo4j.conf` and you should be good.

Not sure if we have the same behaviour for the Windows startup scripts - please check this yourself.

I'm not aware of a way to modify environment variables from with a running JVM - you have to set it from the outside.

**Comment by bandaja** [comment]
Sarmbruster, I tried but same error.
Steps:
1.	I modified the file $NEO4J_HOME\conf\new4j.conf and added at the end the parameter PGGSSENCMODE=disable
2.	I restarted neo4j database
3.	I try to run the script, but I have the same error.
Failed to invoke procedure `apoc.load.jdbc`: Caused by: org.postgresql.util.PSQLException: An error occurred while setting up the GSS Encoded connection.

Any other idea?

Francisco Javier Banda

**Comment by bandaja** [comment]
Error in the  $NEO4J_HOME\logs\neo4j  file.

2020-09-08 18:12:15.987+0000 ERROR Cannot execute SQL statement `SELECT name FROM bandaja.state`.
Error:
An error occurred while setting up the GSS Encoded connection. An error occurred while setting up the GSS Encoded connection.
org.postgresql.util.PSQLException: An error occurred while setting up the GSS Encoded connection.
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableGSSEncrypted(ConnectionFactoryImpl.java:480)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:144)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.connect(Driver.java:264)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at apoc.load.util.JdbcUtil.getConnection(JdbcUtil.java:34)
	at apoc.load.Jdbc.executeQuery(Jdbc.java:82)
	at apoc.load.Jdbc.jdbc(Jdbc.java:66)
	at org.neo4j.kernel.impl.proc.GeneratedProcedure_jdbc1608552921633700.apply(Unknown Source)
	at org.neo4j.procedure.impl.ProcedureRegistry.callProcedure(ProcedureRegistry.java:208)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.callProcedure(GlobalProceduresRegistry.java:323)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:966)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallRead(AllStoreHolder.java:869)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.$anonfun$callReadOnlyProcedure$2(CallSupport.scala:51)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callProcedure(CallSupport.scala:98)
	at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callReadOnlyProcedure(CallSupport.scala:53)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadOnlyProcedure(TransactionBoundQueryContext.scala:880)
	at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext.callReadOnlyProcedure(ExceptionTranslatingQueryContext.scala:203)
	at org.neo4j.cypher.internal.runtime.interpreted.DelegatingQueryContext.callReadOnlyProcedure(DelegatingQueryContext.scala:283)
	at org.neo4j.cypher.internal.runtime.LazyReadOnlyCallMode.callProcedure(ProcedureCallMode.scala:52)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.call(ProcedureCallPipe.scala:87)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$1(ProcedureCallPipe.scala:73)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:70)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:66)
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:59)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:99)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.initiate(StandardInternalExecutionResult.scala:62)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.$anonfun$initiate$1(ClosingExecutionResult.scala:59)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.safely(ClosingExecutionResult.scala:100)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.initiate(ClosingExecutionResult.scala:59)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult$.wrapAndInitiate(ClosingExecutionResult.scala:189)
	at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.innerExecute(CypherCurrentCompiler.scala:354)
	at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:291)
	at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:219)
	at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$execute$1(ExecutionEngine.scala:151)
	at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:185)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:151)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:135)
	at org.neo4j.fabric.executor.FabricKernelTransaction.lambda$execute$0(FabricKernelTransaction.java:91)
	at org.neo4j.fabric.stream.StatementResults.connectVia(StatementResults.java:56)
	at org.neo4j.fabric.executor.FabricKernelTransaction.run(FabricKernelTransaction.java:80)
	at org.neo4j.fabric.executor.FabricLocalExecutor$LocalTransactionContext.run(FabricLocalExecutor.java:93)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.runLocalQueryAt(FabricExecutor.java:374)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.runExec(FabricExecutor.java:343)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.run(FabricExecutor.java:282)
	at org.neo4j.fabric.executor.FabricExecutor$FabricStatementExecution.run(FabricExecutor.java:251)
	at org.neo4j.fabric.executor.FabricExecutor.lambda$run$0(FabricExecutor.java:148)
	at org.neo4j.fabric.transaction.FabricTransactionImpl.execute(FabricTransactionImpl.java:307)
	at org.neo4j.fabric.executor.FabricExecutor.run(FabricExecutor.java:132)
	at org.neo4j.fabric.bolt.BoltFabricDatabaseService$BoltTransactionImpl.executeQuery(BoltFabricDatabaseService.java:165)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractTransactionStateMachineSPI$AbstractBoltResultHandle.start(AbstractTransactionStateMachineSPI.java:135)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:534)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State$2.run(TransactionStateMachine.java:330)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.run(TransactionStateMachine.java:84)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.run(TransactionStateMachine.java:77)
	at org.neo4j.bolt.v4.runtime.InTransactionState.processRunMessage(InTransactionState.java:81)
	at org.neo4j.bolt.v4.runtime.InTransactionState.processUnsafe(InTransactionState.java:48)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:143)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:91)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:90)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:148)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:237)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:172)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:162)
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:246)
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$3(ExecutorBoltScheduler.java:229)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by sarmbruster** [comment]
My answer above just validated that the *linux* start script exposes all config settings as env variables. Not sure about the windows start script. Alternatively you might also set a global env variable `PGGSSENCMODE=disable` - refer to your OS docs on how to do that.

**Comment by vga91** [comment]
@bandaja 
Closed because it is obsolete.
If the problem occurs with new versions of APOC and PostgreSQL, please feel free to reopen the issue
