### ISSUE TITLE
Stored procedure error on neo4j restart

### ISSUE THREAD

**Issue by kraney** [neo4j-contrib/neo4j-apoc-procedures#1744]
## Expected Behavior (Mandatory)

No stack trace on database restart

## Actual Behavior (Mandatory)

After creating a stored procedure, when I restart the DB I get this error:
```
2020-12-03 08:28:15.542+0000 ERROR [neo4j] Could not register procedure: custom.vantagepoint_within_area with 
		MATCH (start:Area {name: $areaName} )
		CALL apoc.path.expand(start,'CONTAINS>|<SEES|CURRENT','',0,100) YIELD path
		UNWIND nodes(path) as node
		WITH node
		WHERE node:VantagePoint
		RETURN DISTINCT node 
	as resource accepting[areaName :: STRING?] resulting in [resource :: NODE?] mode READ
java.lang.UnsupportedOperationException 
	at java.base/java.util.AbstractCollection.add(AbstractCollection.java:267)
	at apoc.custom.CypherProceduresHandler.registerProcedure(CypherProceduresHandler.java:362)
	at apoc.custom.CypherProceduresHandler$ProcedureDescriptor.register(CypherProceduresHandler.java:661) at apoc.custom.CypherProceduresHandler.lambda$restoreProceduresAndFunctions$2(CypherProceduresHandler.java:211)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) at apoc.custom.CypherProceduresHandler.restoreProceduresAndFunctions(CypherProceduresHandler.java:210)
	at apoc.custom.CypherProceduresHandler.available(CypherProceduresHandler.java:120)
	at org.neo4j.internal.helpers.Listeners.notifySingleListener(Listeners.java:126)
	at org.neo4j.internal.helpers.Listeners.notify(Listeners.java:83)
	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:119)
	at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:61)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) at org.neo4j.kernel.database.Database.start(Database.java:480)
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:134)
	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:119)
	at com.neo4j.dbms.Transition$Prepared.doTransitionAction(Transition.java:101)
	at com.neo4j.dbms.Transition$Prepared.doTransition(Transition.java:88)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:347)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:348)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:348)
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$11(DbmsReconciler.java:316)
	at com.neo4j.dbms.DbmsReconciler.namedJob(DbmsReconciler.java:327)
	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:317)
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$9(DbmsReconciler.java:308)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I first thought it was related to having a 'dot' in the name because the name reported is incorrect in this case, but I changed to underscores and it still occurs.

### Simple Dataset (where it's possibile)

```
CALL apoc.custom.asProcedure('vantagepoint_within_area',
  "MATCH (start:Area {name: $areaName} )
    CALL apoc.path.expand(start,'CONTAINS>|<SEES|CURRENT','',0,100) YIELD path
    UNWIND nodes(path) as node
    WITH node
    WHERE node:VantagePoint
    RETURN DISTINCT node as resource",
  'read',
  [['resource','NODE']],
  [['areaName', 'STRING']],
  "Get vantage points within an area and all included areas");
```

### Steps (Mandatory)

  1. Create the procedure as above
  1. Restart Neo4J
  1. Observe the neo4j output

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux (Alpine in Docker)
  - Neo4j: neo4j:4.1.3-enterprise
  - Neo4j-Apoc: apoc-4.1.0.3-all.jar

**Comment by conker84** [comment]
related to #1714

**Comment by rweverwijk** [comment]
@vga91 I think the same bug is in version 4.2, I'm thinking about reapplying your changes on the 4.2 branch as well. What do think?
