### ISSUE TITLE
Neo fails to start with apoc

### ISSUE THREAD

**Issue by nateless** [neo4j-contrib/neo4j-apoc-procedures#259]
```
2017-01-26 14:58:35.482+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1472f289' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1472f289' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1472f289' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1472f289' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$1@42126378' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/api/proc/ProcedureSignature$Mode
	at apoc.schema.AssertSchemaProcedure.signature(AssertSchemaProcedure.java:151)
	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:53)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:103)
	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:76)
	at apoc.ApocKernelExtensionFactory$1.start(ApocKernelExtensionFactory.java:49)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.api.proc.ProcedureSignature$Mode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```

**Comment by iositan** [comment]
F.Y.I 
I had similar error trying to use apoc compiled latest version with neo4j 3.2 (compiled from source).
Check the compatibility matrix

Didn't investigate what is not liking in neo4j 3.2.x

**Comment by sarmbruster** [comment]
Since APOC uses Neo4j non-public API you need to make sure using the right version of Neo4j with the right version of apoc, see the compatibility matrix at https://github.com/neo4j-contrib/neo4j-apoc-procedures#version-compatibility-matrix
As of now, there's now apoc version for 3.2, this will be provided at latest shortely after a 3.2 GA release.

**Comment by nateless** [comment]
@sarmbruster, we are using version 3.1

**Comment by sarmbruster** [comment]
which exact 3.1 version, which apoc version?

**Comment by nateless** [comment]
Neo 3.1.1, APOC 3.0.8.4

**Comment by sarmbruster** [comment]
apoc 3.0.8.4 is for Neo4j 3.0.8 and later 3.0.x
For 3.1 use https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/3.1.0.3
