### ISSUE TITLE
Exclude jackson stuff

### ISSUE THREAD

**Issue by vga91** [neo4j-contrib/neo4j-apoc-procedures#4320]
Exclude jackson stuff and optionally replicate the error with testContainer or so.

To replicate it, enable and run the new query API and got this error:
```
2024-12-19 23:09:41.844+0000 WARN  /db/recommendations/query/v2
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410) ~[jersey-container-servlet-core-2.43.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.43.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:359) ~[jersey-container-servlet-core-2.43.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312) ~[jersey-container-servlet-core-2.43.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.43.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[jetty-servlet-10.0.24.jar:10.0.24]
```

executing this one:
```
curl -X POST -u <user:pwd> "<url>/db/recommendations/query/v2" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -d '{"statement":"RETURN 1 as test","parameters":{}}'
```

**Comment by vga91** [comment]
Most of them are included via testImplementation and apt.

There are also many included via compileOnly, 
which are equally ignored but can be added via extra-dependencies.

These however exclude jackson, e.g. [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extra-dependencies/hadoop/build.gradle#L32) via [`commonExclusions`](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extra-dependencies/build.gradle#L17).

The only two included as “implementations” (and thus integrated into the built jar) are:
- implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-csv', version: '2.15.0',
which is in APOC Core, so not editable 
- implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.17.0', withoutJacksons
which excludes via `withoutJacksons` as well and, in case of issues, we can revert [this commit](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/170b6e05bacc1f5f10f9c7aee11bfb80e8e7ced6) and change it as an extra-dependency.

But atm they do not seem to give conflict problems.
