### ISSUE TITLE
Neo.DatabaseError.General.UnknownError The statement has been closed.

### ISSUE THREAD

**Issue by ctytgat** [neo4j-contrib/neo4j-apoc-procedures#627]
This kind of query worked fine in Neo4j 3.1.0 and Apoc 3.1.0.4.

`MATCH (n:Actor) WHERE n.name IN ["John", "Bruce"] CALL apoc.path.subgraphNodes(n, {maxLevel: 10, relationshipFilter:'KNOWS'}) YIELD node WITH collect(node) as c1, collect(distinct n) as c0 return c0, c1;`

However, doing the same in 3.2.6 (or 3.2.5) with Apoc 3.2.0.4 gives following error. Any idea?
The collect statement seems to be causing the error.

```
org.neo4j.graphdb.NotInTransactionException: The statement has been closed.
	at org.neo4j.kernel.impl.api.KernelStatement.assertOpen(KernelStatement.java:187)
	at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetRelationships(OperationsFacade.java:310)
	at org.neo4j.cypher.internal.spi.v3_2.TransactionBoundQueryContext.getRelationshipsForIds(TransactionBoundQueryContext.scala:134)
	at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext$$anonfun$getRelationshipsForIds$1.apply(ExceptionTranslatingQueryContext.scala:195)
	at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext$$anonfun$getRelationshipsForIds$1.apply(ExceptionTranslatingQueryContext.scala:195)
	at org.neo4j.cypher.internal.spi.v3_2.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
	at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:34)
	at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext.getRelationshipsForIds(ExceptionTranslatingQueryContext.scala:195)
	at org.neo4j.cypher.internal.compiler.v3_2.pipes.ExpandAllPipe$$anonfun$internalCreateResults$1.apply(ExpandAllPipe.scala:42)
	at org.neo4j.cypher.internal.compiler.v3_2.pipes.ExpandAllPipe$$anonfun$internalCreateResults$1.apply(ExpandAllPipe.scala:39)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$hasNext$1.apply$mcZ$sp(ResultIterator.scala:60)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:58)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:58)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:94)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator.decoratedCypherException(ResultIterator.scala:103)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator.failIfThrows(ResultIterator.scala:92)
	at org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator.hasNext(ResultIterator.scala:57)
	at org.neo4j.cypher.internal.compiler.v3_2.PipeExecutionResult.hasNext(PipeExecutionResult.scala:77)
	at org.neo4j.cypher.internal.compiler.v3_2.helpers.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:53)
	at org.neo4j.cypher.internal.compiler.v3_2.PipeExecutionResult.accept(PipeExecutionResult.scala:109)
	at org.neo4j.cypher.internal.compatibility.v3_2.ExecutionResultWrapper.accept(ExecutionResultWrapper.scala:159)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply$mcV$sp(ClosingExecutionResult.scala:169)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.compatibility.v3_2.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.javacompat.ExecutionResult.accept(ExecutionResult.java:318)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:69)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:130)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:449)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:227)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:90)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:448)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:230)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:98)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:123)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:96)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ctytgat** [comment]
Could this be related?
https://github.com/neo4j/neo4j/pull/9764

**Comment by sarmbruster** [comment]
Neo4j 3.2.5, 3.2.6 and 3.1.7 do have a slightly changed behaviour in being more strict regarding closing internal resources. As a side effect a issue was introduced causing trouble when using traversal API inside a stored procedure (what `apoc.path.subgraphNodes` does).
There's already a PR to be merged into Neo4j (https://github.com/neo4j/neo4j/pull/10206). However we need to wait for the next release.
So your options are:
1) go back to previous Neo4j version
2) wait for next release
3) I've built an updated neo4j-kernel.jar (https://drive.google.com/file/d/0B0AxyUhPvHgyU29ucEVCNFB3TGs/view?usp=sharing) containing the referenced PR. You need to copy that to your neo4j lib folder and replace the existing neo4j-kernel-3.2.6.jar. Be aware that you do this on your own risk - it's just a copy from a local build with no massive QA stuff involved.

**Comment by ctytgat** [comment]
Ok thx, we'll stick to 3.1.6 for now!

**Comment by conker84** [comment]
This should be fixed now
