### ISSUE TITLE
apoc.schema.properties.distinctCount closes transaction after first index examined

### ISSUE THREAD

**Issue by lszumel** [neo4j-contrib/neo4j-apoc-procedures#639]
This procedure is closing the transaction in two cases: in the `catch` and `finally` blocks. I can't understand why either is necessary--surely the execution engine will close the transaction on exception? 

The close in the `finally` causes a failure if the label has more than one index. After the first index is looked at, the following exception is thrown.
```

org.neo4j.graphdb.QueryExecutionException: Failed to call procedure `apoc.schema.properties.distinctCount(label =  :: STRING?, key =  :: STRING?) :: (label :: STRING?, key :: STRING?, value :: STRING?, count :: INTEGER?)`: The requested operation cannot be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.

	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:82)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:430)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:413)
	at apoc.util.TestUtil.testResult(TestUtil.java:86)
	at apoc.index.SchemaIndexTest.testDistinctCountPropertiesOnFirstIndex(SchemaIndexTest.java:168)
```

e.g. the following query will throw the above exception:
```
CALL apoc.schema.properties.distinctCount({label}, {key}) YIELD label,key,value,count RETURN * ORDER BY value
```

**Comment by jexp** [comment]
You are right, sorry. That was a wrong implementation and missing test.

This here has to go:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blame/3.2/src/main/java/apoc/index/SchemaIndex.java#L235

**Comment by lszumel** [comment]
OK, I'll add that to my PR as well.
