### ISSUE TITLE
APOC 3.3.0.1 on Neo4J 3.3.3 | ERROR Failed to start Neo4j | Cannot inherit from final class

### ISSUE THREAD

**Issue by pmahend1** [neo4j-contrib/neo4j-apoc-procedures#743]
Getting below exception after installing APOC 3.3.0.1 on Neo4J 3.3.3. This blocks start up of Neo4J DB

**Log**

_WARNING: This command does not appear to be running with administrative rights.  Some commands may fail e.g. Start/Stop
2018-02-16 19:42:33.424+0000 INFO  ======== Neo4j 3.3.3 ========
2018-02-16 19:42:33.503+0000 INFO  Starting...
2018-02-16 19:42:35.443+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-02-16 19:42:35.465+0000 INFO  Initiating metrics...
2018-02-16 19:42:44.718+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3b50f432' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3b50f432' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component **'org.neo4j.server.database.LifecycleManagingDatabase@3b50f432' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)**
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@3b50f432' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\Prateek\AppData\Roaming\Neo4j Desktop\Application\neo4jDatabases\database-86b52006-ba7c-43ae-b394-7d44abc5fd04\installation-3.3.3\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component **'org.neo4j.kernel.impl.proc.Procedures@776a3365' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)**
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:275)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2018-02-16 19:42:44.719+0000 INFO  Neo4j Server shutdown initiated by request_

**Comment by jexp** [comment]
Do you only have apoc installed or also other plugins?

Just tried it with 3.3.3 and apoc 3.3.0.1 and didn't see any issues.

**Comment by pmahend1** [comment]
Other plugins are irrelevant. I had tried installing before installing other ones.
It gets installed but blocks start of the DB server with above error.

```
dbms.security.procedures.unrestricted=algo.*,apoc.*
dbms.security.procedures.whitelist=algo.*,apoc.*,semantics.*
dbms.unmanaged_extension_classes=semantics.extension=/rdf
```

Do you think its due to below setting?

`dbms.jvm.additional=-XX:+TrustFinalNonStaticFields`

**Comment by jexp** [comment]
can you try to remove the neosemantics plugin and try again?

**Comment by pmahend1** [comment]
Thanks. That solved the issue. The neosemantics  plug in was not showing on app, so I thought it was uninstalled too.

**Comment by jexp** [comment]
I'll work with Jesus to resolve it.
