### ISSUE TITLE
apoc.refactor.mergeNodes() has problems coping with uniqueness constraints

### ISSUE THREAD

**Issue by maxthemillion** [neo4j-contrib/neo4j-apoc-procedures#762]
Hi all, 
I just encountered an issue when trying to merge nodes using 

`CALL apoc.refactor.mergeNodes()
`

- Neo4j version: 3.3.1
- apoc version 3.3.0.1
- Operating system: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-101-generic x86_64)
- API/Driver: Cypher Shell

I have nodes with two kinds of labels in the database. Each of them has a uniqueness constraint on one of their properties. When trying to merge both nodes, the shell returns the following message:

``` Could not apply the transaction to the store after written to log ``` (log entry see below)

Based on the log output, I suspect that the uniqueness-constraints are the root to the problem here and that the transaction fails because node A to which all properties of node B should be merged now also holds a duplicate of the constrained property of node B. However, I would expect the procedure to delete node B in the merging process such that node A can be written to the database. 

Is there a workaround for this problem? Thank you for your support!

Code to reproduce this issue:
```
CREATE CONSTRAINT ON (a:A) ASSERT a.prop1 IS UNIQUE;
CREATE CONSTRAINT ON (a:B) ASSERT a.prop2 IS UNIQUE;
CREATE (a:A) SET a.prop1 = 1;
CREATE (b:B) SET b.prop2 = 99;

MATCH (a:A {prop1:1})
MATCH (b:B {prop2:99})
CALL apoc.refactor.mergeNodes([a, b]) YIELD node RETURN node;
```

Log entry
```
2018-03-14 16:52:24.484+0000 ERROR [o.n.k.i.DatabaseHealth] Database panic: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details. Failed to apply transaction: null
org.neo4j.kernel.api.exceptions.TransactionApplyKernelException: Failed to apply transaction: null
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:334)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:597)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:468)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:138)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:398)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:274)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:105)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:461)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:139)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:132)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
Caused by: java.io.IOException: Failed to flush index updates
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.applyPendingLabelAndIndexUpdates(IndexBatchTransactionApplier.java:103)
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.close(IndexBatchTransactionApplier.java:124)
	at org.neo4j.kernel.impl.api.BatchTransactionApplierFacade.close(BatchTransactionApplierFacade.java:70)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:331)
	... 20 more
Caused by: java.util.concurrent.ExecutionException: org.neo4j.kernel.impl.store.UnderlyingStorageException: IndexEntryConflictException{propertyValues=( Long(99) ), addedNodeId=0, existingNodeId=1}
	at org.neo4j.concurrent.WorkSync.checkFailure(WorkSync.java:182)
	at org.neo4j.concurrent.WorkSync.apply(WorkSync.java:91)
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.applyPendingLabelAndIndexUpdates(IndexBatchTransactionApplier.java:99)
	... 23 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: IndexEntryConflictException{propertyValues=( Long(99) ), addedNodeId=0, existingNodeId=1}
	at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:67)
	at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:42)
	at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
	at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
	... 25 more
Caused by: IndexEntryConflictException{propertyValues=( Long(99) ), addedNodeId=0, existingNodeId=1}
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.assertNoConflict(NativeSchemaNumberIndexUpdater.java:148)
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.processAdd(NativeSchemaNumberIndexUpdater.java:138)
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.processUpdate(NativeSchemaNumberIndexUpdater.java:93)
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.process(NativeSchemaNumberIndexUpdater.java:65)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexUpdater.process(FusionIndexUpdater.java:48)
	at org.neo4j.kernel.impl.api.index.updater.UpdateCountingIndexUpdater.process(UpdateCountingIndexUpdater.java:46)
	at org.neo4j.kernel.impl.api.index.updater.DelegatingIndexUpdater.process(DelegatingIndexUpdater.java:40)
	at org.neo4j.kernel.impl.api.index.updater.DelegatingIndexUpdater.process(DelegatingIndexUpdater.java:40)
	at org.neo4j.kernel.impl.api.index.IndexingService.processUpdate(IndexingService.java:454)
	at org.neo4j.kernel.impl.api.index.IndexingService.apply(IndexingService.java:417)
	at org.neo4j.kernel.impl.api.index.IndexingService.apply(IndexingService.java:401)
	at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:63)
	... 28 more
2018-03-14 16:52:24.486+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [TransactionCommitFailed]: Could not apply the transaction to the store after written to log, reference 58ff0985-f4a4-48fe-aa9c-301a5635fb0b.
2018-03-14 16:52:24.486+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [TransactionCommitFailed]: Could not apply the transaction to the store after written to log, reference 58ff0985-f4a4-48fe-aa9c-301a5635fb0b. Could not apply the transaction to the store after written to log
org.neo4j.kernel.api.exceptions.TransactionFailureException: Could not apply the transaction to the store after written to log
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:82)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:597)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:468)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:138)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:398)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:274)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:105)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:461)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:236)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:114)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:139)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:132)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
Caused by: org.neo4j.kernel.api.exceptions.TransactionApplyKernelException: Failed to apply transaction: null
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:334)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
	... 19 more
Caused by: java.io.IOException: Failed to flush index updates
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.applyPendingLabelAndIndexUpdates(IndexBatchTransactionApplier.java:103)
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.close(IndexBatchTransactionApplier.java:124)
	at org.neo4j.kernel.impl.api.BatchTransactionApplierFacade.close(BatchTransactionApplierFacade.java:70)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:331)
	... 20 more
Caused by: java.util.concurrent.ExecutionException: org.neo4j.kernel.impl.store.UnderlyingStorageException: IndexEntryConflictException{propertyValues=( Long(99) ), addedNodeId=0, existingNodeId=1}
	at org.neo4j.concurrent.WorkSync.checkFailure(WorkSync.java:182)
	at org.neo4j.concurrent.WorkSync.apply(WorkSync.java:91)
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier.applyPendingLabelAndIndexUpdates(IndexBatchTransactionApplier.java:99)
	... 23 more
Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: IndexEntryConflictException{propertyValues=( Long(99) ), addedNodeId=0, existingNodeId=1}
	at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:67)
	at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:42)
	at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
	at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
	... 25 more
Caused by: IndexEntryConflictException{propertyValues=( Long(99) ), addedNodeId=0, existingNodeId=1}
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.assertNoConflict(NativeSchemaNumberIndexUpdater.java:148)
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.processAdd(NativeSchemaNumberIndexUpdater.java:138)
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.processUpdate(NativeSchemaNumberIndexUpdater.java:93)
	at org.neo4j.kernel.impl.index.schema.NativeSchemaNumberIndexUpdater.process(NativeSchemaNumberIndexUpdater.java:65)
	at org.neo4j.kernel.impl.index.schema.fusion.FusionIndexUpdater.process(FusionIndexUpdater.java:48)
	at org.neo4j.kernel.impl.api.index.updater.UpdateCountingIndexUpdater.process(UpdateCountingIndexUpdater.java:46)
	at org.neo4j.kernel.impl.api.index.updater.DelegatingIndexUpdater.process(DelegatingIndexUpdater.java:40)
	at org.neo4j.kernel.impl.api.index.updater.DelegatingIndexUpdater.process(DelegatingIndexUpdater.java:40)
	at org.neo4j.kernel.impl.api.index.IndexingService.processUpdate(IndexingService.java:454)
	at org.neo4j.kernel.impl.api.index.IndexingService.apply(IndexingService.java:417)
	at org.neo4j.kernel.impl.api.index.IndexingService.apply(IndexingService.java:401)
	at org.neo4j.kernel.impl.transaction.command.IndexUpdatesWork.apply(IndexUpdatesWork.java:63)
	... 28 more```

**Comment by jexp** [comment]
It's a bug in neo4j which has been resolved here and should be available in neo4j 3.3.4 soon:

https://github.com/neo4j/neo4j/pull/11009

**Comment by maxthemillion** [comment]
Ok good to know. Thank you! Is there a workaround to deal with this in the meantime?

**Comment by arentschler** [comment]
@jexp This issue https://github.com/neo4j/neo4j/pull/11009 is now closed and merged with v.3.3.3. So, do we need to wait for 3.3.4 for https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/762 to be resolved?

**Comment by jexp** [comment]
Yes, which has been released. So please try again, so that we can close the issue.

**Comment by maxthemillion** [comment]
I just tried it and it works for me, now. Thanks 👍

**Comment by jvhashe** [comment]
Can we reopen this issue? I've been experiencing the same issue in APOC versions 3.4.X and 3.5.X. Since the original solution to this bug was a fix directly in Neo4j, I contacted their support staff. After looking into it, they claim it's a bug in APOC. Here's their response.

> This is an APOC bug because it tries to write the source properties on the target node before the target node is deleted: 
>https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3f74d1c37a024195e373b001ae353d77c402776e/src/main/java/apoc/refactor/GraphRefactoring.java#L481-L499 
>If they first copied the source node properties, then deleted the source node, and then write the properties to the target node, then it would work. The test that is added in his original PR proves this:
>https://github.com/neo4j/neo4j/blob/3.5/community/community-it/index-it/src/test/java/org/neo4j/kernel/api/impl/index/AccidentalUniquenessConstraintViolationIT.java
