### ISSUE TITLE
"class not found" error using similarity option for apoc.index.addAllNodes

### ISSUE THREAD

**Issue by charleskoehl** [neo4j-contrib/neo4j-apoc-procedures#887]
When I use the similarity option for apoc.index.addAllNodes, it silently fails, preventing the index from being created. No errors are reported in the browser, and the result is simply “(no changes, no records).” There is an error in the logs though, which I added after the examples below.

The following examples create no indexes, and output “(no changes, no records)”: 

```
CALL apoc.index.addAllNodes('foods', {Food: ['name','aka','commodity','variety']},{similarity:'TFIDFSimilarity'})

// Same with this one:
CALL apoc.index.addAllNodes('foods', {Food: ['name','aka','commodity','variety']},{similarity:'org.apache.lucene.search.similarities.TFIDFSimilarity'})

// The similarity class name seems to be ignored completely:
CALL apoc.index.addAllNodes('foods', {Food: ['name','aka','commodity','variety']},{similarity:''})
```

The same call without the similarity option works:
```
CALL apoc.index.addAllNodes('foods', {Food: ['name','aka','commodity','variety']})
```

I've also tried the other classes: BM25Similarity, MultiSimilarity, PerFieldSimilarityWrapper, SimilarityBase.

This is the error in the logs for the first example:
```
2018-08-15 17:22:47.460+0000 INFO  Creating or updating index 'foods' with config '{type=fulltext, to_lower_case=true, provider=lucene, keysForLabel:Food=name:akaIFPS:commodityIFPS:varietyIFPS:varietyNewIFPS:varietyPMA, similarity=TFIDFSimilarity, labels=Food}'
Exception in thread "pool-28-thread-2" java.lang.RuntimeException: java.lang.ClassNotFoundException: TFIDFSimilarity
	at org.neo4j.index.impl.lucene.explicit.IndexType.getByClassName(IndexType.java:275)
	at org.neo4j.index.impl.lucene.explicit.IndexType.getCustomSimilarity(IndexType.java:256)
	at org.neo4j.index.impl.lucene.explicit.IndexType.getIndexType(IndexType.java:186)
	at org.neo4j.index.impl.lucene.explicit.LuceneIndexImplementation.fillInDefaults(LuceneIndexImplementation.java:131)
	at org.neo4j.kernel.impl.index.ExplicitIndexStore.findIndexConfig(ExplicitIndexStore.java:110)
	at org.neo4j.kernel.impl.index.ExplicitIndexStore.getOrCreateIndexConfig(ExplicitIndexStore.java:163)
	at org.neo4j.kernel.impl.index.ExplicitIndexStore.getOrCreateNodeIndexConfig(ExplicitIndexStore.java:68)
	at org.neo4j.kernel.impl.newapi.AllStoreHolder.getOrCreateNodeIndexConfig(AllStoreHolder.java:779)
	at org.neo4j.kernel.impl.newapi.Operations.nodeExplicitIndexCreateLazily(Operations.java:669)
	at org.neo4j.kernel.impl.coreapi.IndexProviderImpl.getOrCreateNodeIndex(IndexProviderImpl.java:56)
	at org.neo4j.kernel.impl.coreapi.IndexManagerImpl.forNodes(IndexManagerImpl.java:81)
	at apoc.index.FreeTextSearch.index(FreeTextSearch.java:226)
	at apoc.index.FreeTextSearch.lambda$addAllNodes$0(FreeTextSearch.java:66)
	at apoc.util.AsyncStream.lambda$async$0(AsyncStream.java:20)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: TFIDFSimilarity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.neo4j.index.impl.lucene.explicit.IndexType.getByClassName(IndexType.java:271)
	... 16 more
```

APOC 3.4.0.1
Neo4j 3.4.4 Enterprise

**Comment by jexp** [comment]
@sarmbruster do you have an idea?

**Comment by sarmbruster** [comment]
TFIDFSimilarity is an abstract class, see https://lucene.apache.org/core/5_5_5/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html#TFIDFSimilarity--

Using
```
CALL apoc.index.addAllNodes('foods', {Food: ['name','aka','commodity','variety']},{similarity:'org.apache.lucene.search.similarities.BM25Similarity'});
```
an index can be established without any error. Please confirm this.
