### ISSUE TITLE
apoc.import.csv creates superflous nodes when relationship references don't exist

### ISSUE THREAD

**Issue by ArthurClemens** [neo4j-contrib/neo4j-apoc-procedures#951]
Test case, using the example from "Loading nodes and relationships":

`/tmp/persons.csv`:
```
:ID,name:STRING,speaks:STRING[]
1,John,"en,fr"
2,Jane,"en,de"
```

`/tmp/knows.csv`:
```
:START_ID,:END_ID,since:INT
1,2,2016
10,11,2014
11,12,2013
```
(note the 2 extra lines)

Command:
```
CALL apoc.import.csv(
  [{fileName: '/tmp/persons.csv', labels: ['Person']}],
  [{fileName: '/tmp/knows.csv', type: 'KNOWS'}],
  {stringIds: false}
)
```

The result creates 6 nodes - John and Jane are tripled:
```
╒═══════════════════════════════════════════════╕
│"n"                                            │
╞═══════════════════════════════════════════════╡
│{"name":"John","speaks":["en,fr"],"__csv_id":1}│
├───────────────────────────────────────────────┤
│{"name":"Jane","speaks":["en,de"],"__csv_id":2}│
├───────────────────────────────────────────────┤
│{"name":"John","speaks":["en,fr"],"__csv_id":1}│
├───────────────────────────────────────────────┤
│{"name":"Jane","speaks":["en,de"],"__csv_id":2}│
├───────────────────────────────────────────────┤
│{"name":"John","speaks":["en,fr"],"__csv_id":1}│
├───────────────────────────────────────────────┤
│{"name":"Jane","speaks":["en,de"],"__csv_id":2}│
└───────────────────────────────────────────────┘
```

This is the full response:
```
[
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 393,
          "high": 0
        },
        "labels": [
          "Person"
        ],
        "properties": {
          "name": "John",
          "speaks": [
            "en,fr"
          ],
          "__csv_id": {
            "low": 1,
            "high": 0
          }
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 394,
          "high": 0
        },
        "labels": [
          "Person"
        ],
        "properties": {
          "name": "Jane",
          "speaks": [
            "en,de"
          ],
          "__csv_id": {
            "low": 2,
            "high": 0
          }
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 414,
          "high": 0
        },
        "labels": [
          "Person"
        ],
        "properties": {
          "name": "John",
          "speaks": [
            "en,fr"
          ],
          "__csv_id": {
            "low": 1,
            "high": 0
          }
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 415,
          "high": 0
        },
        "labels": [
          "Person"
        ],
        "properties": {
          "name": "Jane",
          "speaks": [
            "en,de"
          ],
          "__csv_id": {
            "low": 2,
            "high": 0
          }
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 488,
          "high": 0
        },
        "labels": [
          "Person"
        ],
        "properties": {
          "name": "John",
          "speaks": [
            "en,fr"
          ],
          "__csv_id": {
            "low": 1,
            "high": 0
          }
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 489,
          "high": 0
        },
        "labels": [
          "Person"
        ],
        "properties": {
          "name": "Jane",
          "speaks": [
            "en,de"
          ],
          "__csv_id": {
            "low": 2,
            "high": 0
          }
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  }
]
```

I tried to prevent this by setting a constraint on `name`, but that doesn't prevent the nodes from being created: they will be created without a name and without a relationship. Related but likely a different bug.

**Comment by jexp** [comment]
@szarnyasg can you have a look?

**Comment by szarnyasg** [comment]
@jexp sure - I did not notice this issue before.

@ArthurClemens thanks for the detailed error report.

I think the underlying issue is that this CSV loader was designed to work with _very clean data_, i.e. the assumption is that there are no missing nodes, no type conversion errors. If anything is wrong, the load crashes.

Now, I added the test case from https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/951#issue-369571828 in commit https://github.com/szarnyasg/neo4j-apoc-procedures/commit/c9ad03bd127400c59f651a887d2117615de83c10.

However, for me, it does not create duplicate nodes, but simply blows us spectacularly (which I'd say is the expected behaviour):

```console
org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.import.csv`: Caused by: java.lang.IllegalStateException: Node for id space __CSV_DEFAULT_IDSPACE and id 10 not found

	at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:83)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:428)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:411)
	at apoc.util.TestUtil.testResult(TestUtil.java:89)
	at apoc.util.TestUtil.testCall(TestUtil.java:38)
	at apoc.export.csv.ImportCsvTest.testNoDuplicationsCreated(ImportCsvTest.java:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
```

@ArthurClemens can you check my test case?

**Comment by ArthurClemens** [comment]
Looks fine!

**Comment by szarnyasg** [comment]
@ArthurClemens thanks for confirming. I submitted a PR with your tests.
