### ISSUE TITLE
Failed to invoke procedure `apoc.import.graphml`: Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by makpcheng** [neo4j-contrib/neo4j-apoc-procedures#996]
## Guidelines

On neo4j community edition 3.4.9, apoc version 3.4.0.3.  I'm able to successfully import a graphml file around 350MB successfully. However when I attempt the same operation on a larger graphml file (10GB) with similar data I'm getting the error message:

Failed to invoke procedure `apoc.import.graphml`: Caused by: java.lang.NullPointerException

## Expected Behavior (Mandatory)
I would expect the import to run successfully. Even if it failed to import, it should fail more gracefully explaining what was the cause the failure.

## Actual Behavior (Mandatory)
Actual Behavior: Operation failed with the given error message: Failed to invoke procedure org.neo4j.driver.v1.exceptions.ClientException: Failed to invoke procedure `apoc.import.graphml`: Caused by: java.lang.NullPointerException
        at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:61)
        at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:137)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$ReaderV1.unpackFailureMessage(PackStreamMessageFormatV1.java:336)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$ReaderV1.read(PackStreamMessageFormatV1.java:300)
        at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:82)
        at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:34)
        at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:39)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1389)
        at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
        at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1203)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

## How to Reproduce the Problem
Simply call import on a large graphml file (say 10GB).

### Simple Dataset (where it's possibile)
Unfortunately the file that's causing this failure is 10GB. The smaller data size at 350MB doesn't have an issue with importing.

//Insert here a set of Cypher statements that helps us to reproduce the problem

CALL apoc.import.graphml('/home/graphml2.gml',{batchSize: 100000});

### Steps (Mandatory)

  1. Setup neo4j to have apoc import enabled
  2. Attempt to import a graphml file that is very large (10GB)

## Specifications (Mandatory)
See versions below...

Currently used versions

### Versions

  - OS: Red Hat Enterprise Linux Server release 6.10 (Santiago) 
  - Neo4j: Community Edition 3.4.9
  - Neo4j-Apoc: 3.4.0.3

**Comment by jexp** [comment]
Can you share your server's debug.log

**Comment by makpcheng** [comment]
@jexp I've attached the servers debug.log file. I looked in there earlier and couldn't find anything useful to me. Thanks

[debug.log](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/2609096/debug.log)

**Comment by jexp** [comment]
Hmm, weird. We have to check the code again about batching the imports.
What's your memory setup ? (page-cache, heap config)

But without the file it will be hard to reproduce. Perhaps you can share a zipped version privately?

**Comment by makpcheng** [comment]
@jexp the heap was set up to 20GB for neo4j on a 32GB system.  2GB set up as the page cache. 

:free -m
             total       used       free     shared    buffers     cached
Mem:         32099      31815        283          2        393       2291
-/+ buffers/cache:      29131       2968
Swap:        34287        360      33927

I see neo4j using up 87% of the systems memory after attempting to import and almost all  system memory is being used up.

Yes I can share a zipped version of the graphml file privately. Please let me know how to share it with you. After zipping the file size is about 842 MB.

**Comment by makpcheng** [comment]
@jexp I've sent a shared google drive file with your to your email.  Please confirm you have received it.

**Comment by jexp** [comment]
Got it, thanks!

**Comment by conker84** [comment]
this should be fixed by #1814 feel free to reopen in case the bug come back!
